/**
 * Catalogue data loader — the three JSON files under ./data, imported as JSON modules (tsc copies them to
 * dist; Node ESM needs the import attribute).
 *
 * The files are generated by scripts/build-flow-catalog.mjs from Flow Designer definitions exported from a
 * ServiceNow instance (catalog/source: sys_hub_trigger_definition / _input / _output, sys_hub_action_type_snapshot,
 * sys_hub_action_input / _output, sys_hub_flow_logic_definition / _input / _variable, sys_choice). They hold
 * platform facts only — names, types, defaults, references, attributes, choices, definition order — plus the
 * label prefixes observed on UI-built flows. Do not hand-edit them; re-export and re-run the script
 * (src/flow-builder/README.md, "Catalogue").
 *
 * Owner: GENERATOR.
 */
import triggersJson from './data/triggers.json' with { type: 'json' };
import actionsJson from './data/actions.json' with { type: 'json' };
import logicJson from './data/logic.json' with { type: 'json' };
import tablesJson from './data/tables.json' with { type: 'json' };

// ─── Shapes ──────────────────────────────────────────────────────────────────

export interface CatalogChoice { value: string; label: string }

/** A definition variable (trigger / action / logic input or output) as the instance defines it. */
export interface CatalogInputRaw {
  name: string;
  label: string;
  /** Flow Designer type: internal_type, or attributes.uiType for a complex object (co_type_name). */
  type: string;
  mandatory?: boolean;
  /** default_value, typed by `type` (boolean / integer); absent when the definition has none. */
  default?: string | number | boolean;
  /** Definition order (the variables are stored sorted by it, then by name). */
  order?: number;
  /** Hidden in Flow Designer (attributes visible / visible_in_fd / visible_in_ui = false). */
  hidden?: boolean;
  attributes?: Record<string, string>;
  reference?: string;
  /** Label of the referenced table (sys_db_object) — trigger inputs, and action inputs / outputs whose table tables.json lists. */
  reference_display?: string;
  maxLength?: number;
  choices?: CatalogChoice[];
  /** dependent_on_field, and whether the definition uses it (use_dependent_field). */
  dependent?: string;
  use_dependent?: boolean;
  /** sys_id of the definition row (trigger inputs: always; action inputs: where the supplement export lists the snapshot input). */
  sys_id?: string;
  /** read_only column of the definition row (Workflow Studio's parameter.readOnly). */
  read_only?: boolean;
  /** hint column of the definition row (parameter.hint). */
  hint?: string;
  /** The `choice` column when set and not 0 (parameter.choiceOption: 1 = dropdown with none, 3 = dropdown without none). */
  choice_option?: string;
}

/** A table Workflow Studio names in label_cache / displayValue / parameter mirrors (tables.json). */
export interface TableInfo {
  name: string;
  /** sys_db_object label ('Requested Item'). */
  label: string;
  /** The table's display field (sys_dictionary display=true), where a UI-built row showed it (parameter.fSearchField). */
  display_field?: string;
}

export interface CatalogOutputRaw extends CatalogInputRaw {
  /** The label Workflow Studio shows for this output in pill labels, where it differs from the definition label. */
  pill_label?: string;
}

/** One entry of a trigger instance's `trigger_inputs` array. */
export interface TriggerDescriptorEntry {
  triggerInstanceSysId: string;
  label: string;
  internalType: string;
  dependent: string;
  choiceList: { fValue: string; fLabel: string; fImage: string; fSelected: boolean; fUsed: boolean; fMissing: boolean }[];
  mandatory: boolean;
  order: number;
  name: string;
  value: unknown;
  displayValue: string;
  displayField: string;
  scriptActive: boolean;
  valueSysId?: string;
  children: unknown[];
  parameter: Record<string, unknown>;
}

export interface TriggerDef {
  key: string;            // the FlowSpec trigger type, 'record.created'
  sys_id: string;         // sys_hub_trigger_definition
  name: string;           // 'Created'
  trigger_type: string;   // 'record_create'
  pill_prefix: string;    // 'Created_1'
  label_prefix: string;   // 'Trigger - Record Created'
  /** false when no UI-built flow on the instance showed the label prefix (then "Trigger - <name>"). */
  label_prefix_verified: boolean;
  inputs: CatalogInputRaw[];
  outputs: CatalogOutputRaw[];
}

export interface ActionDef {
  key: string;            // 'lookUpRecord'
  sys_id: string;         // the sys_hub_action_type_snapshot the UI writes into action_type
  definition: string;     // its sys_hub_action_type_definition (parent_action), written into action_type_parent
  internal_name: string;  // 'look_up_record'
  name: string;           // 'Look Up Record'
  inputs: CatalogInputRaw[];
  outputs: CatalogOutputRaw[];
  /** Stored values of hidden inputs without a default, as Workflow Studio writes them (by input name). */
  hidden_values?: Record<string, string>;
}

export interface LogicInputRaw extends CatalogInputRaw { id: string }

export interface LogicDef {
  key: string;            // the FlowSpec step kind, 'if'
  sys_id: string;         // sys_hub_flow_logic_definition
  name: string;           // 'If'
  type: string;           // 'IF'
  inputs: LogicInputRaw[];
  outputs: CatalogOutputRaw[];
}

export interface CatalogData {
  triggers: TriggerDef[];
  actions: ActionDef[];
  logic: LogicDef[];
  /** Key order of a logic row's values object, as UI-built rows store it. */
  logicValuesKeyOrder: readonly string[];
  /** Table labels (and display fields) by table name. */
  tables: Map<string, TableInfo>;
}

let cache: CatalogData | undefined;

/** The memoised catalogue. */
export function catalogData(): CatalogData {
  if (cache) return cache;
  const t = triggersJson as unknown as { triggers: TriggerDef[] };
  const a = actionsJson as unknown as { actions: ActionDef[] };
  const l = logicJson as unknown as { values_key_order: string[]; logic: LogicDef[] };
  const tb = tablesJson as unknown as { tables: TableInfo[] };
  cache = { triggers: t.triggers, actions: a.actions, logic: l.logic, logicValuesKeyOrder: l.values_key_order, tables: new Map(tb.tables.map(x => [x.name, x])) };
  return cache;
}

/** The sys_db_object label of a table the catalogue knows, else undefined. */
export function knownTableLabel(table: string): string | undefined {
  return catalogData().tables.get(table)?.label;
}

/** The display field of a table the catalogue knows (parameter.fSearchField), else undefined. */
export function knownTableDisplayField(table: string): string | undefined {
  return catalogData().tables.get(table)?.display_field;
}

/** Deep clone via JSON (all catalogue structures are plain JSON). */
export function cloneJson<T>(v: T): T {
  return JSON.parse(JSON.stringify(v)) as T;
}
