/**
 * PDF report generator using pdfmake.
 * Produces branded, multi-page PDF with charts, tables, and ServiceNow links.
 */
import type { ReportData, ReportResult, Severity } from './types.js';
import { BRAND, FONT_SIZES, severityColor, severityLabel, buildRecordLink, linkifyTextPdf } from './brand.js';
import { severityPieChart, categoryBarChart } from './charts.js';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

/** Generate a branded PDF from ReportData. Returns file path and size. */
export async function generatePdf(data: ReportData, outputPath: string): Promise<ReportResult> {
  const { writeFileSync } = await import('fs');

  // pdfmake v0.3: CJS module, use .default from ESM dynamic import
  const pdfmake = (await import('pdfmake/build/pdfmake.js')).default;
  const vfsFonts = (await import('pdfmake/build/vfs_fonts.js')).default;

  // Register virtual file system for embedded Roboto fonts
  pdfmake.addVirtualFileSystem(vfsFonts);

  const content: any[] = [];

  // ─── Cover Page ────────────────────────────────────────────────────────
  content.push({
    stack: [
      { text: '', margin: [0, 80, 0, 0] },
      {
        canvas: [
          { type: 'rect', x: 0, y: 0, w: 515, h: 4, r: 2, color: BRAND.teal },
        ],
      },
      { text: data.title, style: 'coverTitle', margin: [0, 30, 0, 10] },
      { text: data.capability ? `Capability: ${data.capability}` : '', style: 'coverSubtitle', margin: [0, 0, 0, 5] },
      {
        text: data.instanceUrl,
        link: data.instanceUrl,
        style: 'coverLink',
        margin: [0, 5, 0, 5],
      },
      { text: `Instance: ${data.instanceName}`, style: 'coverDetail', margin: [0, 5, 0, 5] },
      { text: `Report Date: ${data.scanDate}`, style: 'coverDetail', margin: [0, 5, 0, 40] },
      {
        canvas: [
          { type: 'rect', x: 0, y: 0, w: 515, h: 2, r: 1, color: BRAND.grayLight },
        ],
      },
      { text: 'Generated by ServiceNow MCP Toolkit', style: 'coverFooter', margin: [0, 15, 0, 0] },
      { text: 'servicenow-mcp.com', link: 'https://servicenow-mcp.com', style: 'coverFooterLink' },
    ],
    pageBreak: 'after',
  });

  // ─── Executive Summary ─────────────────────────────────────────────────
  content.push({ text: 'Executive Summary', style: 'sectionHeader', margin: [0, 0, 0, 15] });

  // Health badge
  if (data.metrics.overallHealth) {
    const healthColor = data.metrics.overallHealth === 'healthy' ? BRAND.healthy
      : data.metrics.overallHealth === 'degraded' ? BRAND.degraded : BRAND.criticalHealth;
    content.push({
      columns: [
        { text: 'Overall Health: ', style: 'bodyBold', width: 'auto' },
        {
          text: ` ${data.metrics.overallHealth.toUpperCase()} `,
          color: BRAND.white,
          background: healthColor,
          bold: true,
          fontSize: 11,
          margin: [5, 0, 0, 0],
          width: 'auto',
        },
      ],
      margin: [0, 0, 0, 10],
    });
  }

  // Severity count boxes
  const severityBoxes = SEVERITY_ORDER.map(sev => ({
    stack: [
      { text: data.metrics.severityCounts[sev].toString(), style: 'metricValue', color: severityColor(sev) },
      { text: severityLabel(sev), style: 'metricLabel' },
    ],
    width: '*',
    alignment: 'center' as const,
  }));

  content.push({
    columns: severityBoxes,
    margin: [0, 5, 0, 15],
  });

  content.push({ text: `Total Findings: ${data.metrics.totalFindings}`, style: 'body', margin: [0, 0, 0, 10] });

  if (data.executiveSummary) {
    content.push({ text: linkifyTextPdf(data.executiveSummary, data.instanceUrl, { fontSize: FONT_SIZES.body, color: BRAND.text }), margin: [0, 0, 0, 10] });
  }

  // ─── Charts ────────────────────────────────────────────────────────────
  if (data.metrics.totalFindings > 0) {
    content.push({ text: '', pageBreak: 'before' });
    content.push({ text: 'Findings Distribution', style: 'sectionHeader', margin: [0, 0, 0, 15] });

    const pieSvg = severityPieChart(data.metrics.severityCounts, 180);
    const barSvg = categoryBarChart(data.metrics.categoryBreakdown, 280);

    content.push({
      columns: [
        {
          stack: [
            { text: 'By Severity', style: 'chartTitle', margin: [0, 0, 0, 8] },
            { svg: pieSvg, width: 180 },
          ],
          width: '45%',
        },
        {
          stack: [
            { text: 'By Category', style: 'chartTitle', margin: [0, 0, 0, 8] },
            { svg: barSvg, width: 280 },
          ],
          width: '55%',
        },
      ],
      margin: [0, 0, 0, 20],
    });
  }

  // ─── Findings by Section ───────────────────────────────────────────────
  for (const section of data.sections) {
    if (section.findings.length === 0 && section.tables.length === 0) continue;

    content.push({
      text: [
        { text: section.title, style: 'sectionHeader' },
        section.findings.length > 0
          ? { text: `  (${section.findings.length} findings)`, style: 'findingCount' }
          : { text: '' },
      ],
      margin: [0, 15, 0, 10],
    });

    // Findings table
    if (section.findings.length > 0) {
      const tableBody: any[][] = [
        [
          { text: 'Severity', style: 'tableHeader' },
          { text: 'Finding', style: 'tableHeader' },
          { text: 'Impact', style: 'tableHeader' },
          { text: 'Recommendation', style: 'tableHeader' },
        ],
      ];

      for (const finding of section.findings) {
        const findingStack: any[] = [
          { text: linkifyTextPdf(finding.title, data.instanceUrl, { bold: true, fontSize: 9 }) },
        ];
        if (finding.description !== finding.title) {
          findingStack.push({ text: linkifyTextPdf(finding.description, data.instanceUrl, { fontSize: 8, color: BRAND.textLight }), margin: [0, 2, 0, 0] });
        }
        if (finding.evidence) {
          findingStack.push({ text: linkifyTextPdf(finding.evidence, data.instanceUrl, { fontSize: 7, color: BRAND.gray, italics: true }), margin: [0, 2, 0, 0] });
        }
        if (finding.table && finding.sysId) {
          findingStack.push({
            text: 'View in ServiceNow',
            link: buildRecordLink(data.instanceUrl, finding.table, finding.sysId),
            fontSize: 8, color: BRAND.teal, decoration: 'underline', margin: [0, 2, 0, 0],
          });
        }

        const row: any[] = [
          { text: severityLabel(finding.severity), color: severityColor(finding.severity), bold: true, fontSize: 9 },
          { stack: findingStack },
          { text: linkifyTextPdf(finding.impact || '—', data.instanceUrl, { fontSize: 9, color: BRAND.textLight }) },
          { text: linkifyTextPdf(finding.recommendation || '—', data.instanceUrl, { fontSize: 9 }) },
        ];
        tableBody.push(row);
      }

      content.push({
        table: {
          headerRows: 1,
          widths: [55, '*', '*', '*'],
          body: tableBody,
        },
        layout: {
          hLineColor: () => BRAND.grayLight,
          vLineColor: () => BRAND.grayLight,
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          paddingLeft: () => 6,
          paddingRight: () => 6,
          paddingTop: () => 4,
          paddingBottom: () => 4,
          fillColor: (rowIndex: number) => rowIndex === 0 ? BRAND.offWhite : null,
        },
        margin: [0, 0, 0, 10],
      });
    }

    // Data tables from markdown
    for (const table of section.tables) {
      const tableBody: any[][] = [
        table.headers.map(h => ({ text: h, style: 'tableHeader' })),
        ...table.rows.map(row => row.map(cell => ({ text: linkifyTextPdf(cell, data.instanceUrl, { fontSize: 9 }) }))),
      ];

      content.push({
        table: {
          headerRows: 1,
          widths: Array(table.headers.length).fill('*'),
          body: tableBody,
        },
        layout: {
          hLineColor: () => BRAND.grayLight,
          vLineColor: () => BRAND.grayLight,
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          paddingLeft: () => 5,
          paddingRight: () => 5,
          paddingTop: () => 3,
          paddingBottom: () => 3,
          fillColor: (rowIndex: number) => rowIndex === 0 ? BRAND.offWhite : null,
        },
        margin: [0, 5, 0, 10],
      });
    }
  }

  // ─── Build PDF Document Definition ─────────────────────────────────────
  const docDefinition: any = {
    content,
    defaultStyle: {
      font: 'Roboto',
      fontSize: FONT_SIZES.body,
      color: BRAND.text,
    },
    styles: {
      coverTitle: { fontSize: FONT_SIZES.title, bold: true, color: BRAND.navy },
      coverSubtitle: { fontSize: FONT_SIZES.subtitle, color: BRAND.teal },
      coverLink: { fontSize: 12, color: BRAND.teal, decoration: 'underline' },
      coverDetail: { fontSize: 12, color: BRAND.textLight },
      coverFooter: { fontSize: 10, color: BRAND.gray, alignment: 'center' },
      coverFooterLink: { fontSize: 10, color: BRAND.teal, decoration: 'underline', alignment: 'center' },
      sectionHeader: { fontSize: FONT_SIZES.sectionHeader, bold: true, color: BRAND.navy },
      chartTitle: { fontSize: 13, bold: true, color: BRAND.navy },
      body: { fontSize: FONT_SIZES.body, color: BRAND.text },
      bodyBold: { fontSize: FONT_SIZES.body, bold: true, color: BRAND.text },
      metricValue: { fontSize: 24, bold: true, alignment: 'center' },
      metricLabel: { fontSize: 9, color: BRAND.textLight, alignment: 'center' },
      findingCount: { fontSize: 11, color: BRAND.gray },
      tableHeader: { fontSize: 9, bold: true, color: BRAND.navy },
      small: { fontSize: FONT_SIZES.small, color: BRAND.textLight },
    },
    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        { text: `ServiceNow MCP Toolkit | servicenow-mcp.com`, fontSize: 8, color: BRAND.gray, margin: [40, 0, 0, 0] },
        { text: data.instanceName, fontSize: 8, color: BRAND.gray, alignment: 'center' },
        { text: `Page ${currentPage} of ${pageCount}`, fontSize: 8, color: BRAND.gray, alignment: 'right', margin: [0, 0, 40, 0] },
      ],
      margin: [0, 10, 0, 0],
    }),
    pageMargins: [40, 40, 40, 50],
  };

  // Generate PDF buffer using pdfmake v0.3 promise-based API
  const doc = pdfmake.createPdf(docDefinition);
  const buffer = await doc.getBuffer();
  const nodeBuffer = Buffer.from(buffer);
  writeFileSync(outputPath, nodeBuffer);
  return { filePath: outputPath, sizeBytes: nodeBuffer.length };
}
