/**
 * PPTX slide deck generator using pptxgenjs.
 * Produces branded presentation with native charts and tables.
 */
import type { ReportData, ReportResult, Severity } from './types.js';
import { BRAND, severityColor, severityLabel, buildRecordLink, linkifyTextPptx } from './brand.js';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

/** Generate a branded PPTX from ReportData. Returns file path and size. */
export async function generatePptx(data: ReportData, outputPath: string): Promise<ReportResult> {
  const PptxGenJS = (await import('pptxgenjs')).default;
  const { statSync } = await import('fs');

  const pptx = new PptxGenJS();
  pptx.author = 'ServiceNow MCP Toolkit';
  pptx.company = 'ServiceNow MCP Toolkit';
  pptx.title = data.title;
  pptx.subject = `${data.capability} report for ${data.instanceName}`;

  // Define master slides
  pptx.defineSlideMaster({
    title: 'BRANDED',
    background: { color: BRAND.white },
    objects: [
      // Top teal bar
      { rect: { x: 0, y: 0, w: '100%', h: 0.06, fill: { color: BRAND.teal.replace('#', '') } } },
      // Bottom bar with branding
      { rect: { x: 0, y: 7.2, w: '100%', h: 0.3, fill: { color: BRAND.offWhite.replace('#', '') } } },
      {
        text: {
          text: 'ServiceNow MCP Toolkit | servicenow-mcp.com',
          options: { x: 0.3, y: 7.22, w: 3, h: 0.25, fontSize: 8, color: BRAND.gray.replace('#', '') },
        },
      },
      {
        text: {
          text: data.instanceName,
          options: { x: 7, y: 7.22, w: 3, h: 0.25, fontSize: 8, color: BRAND.gray.replace('#', ''), align: 'right' },
        },
      },
    ],
  });

  // ─── Slide 1: Title ────────────────────────────────────────────────────
  const titleSlide = pptx.addSlide();
  // Gradient-like background using two rects
  titleSlide.addShape('rect', { x: 0, y: 0, w: '100%', h: '100%', fill: { color: BRAND.navy.replace('#', '') } });
  titleSlide.addShape('rect', { x: 0, y: 0, w: '100%', h: 0.1, fill: { color: BRAND.teal.replace('#', '') } });

  titleSlide.addText(data.title, {
    x: 0.8, y: 1.5, w: 8.4, h: 1.5,
    fontSize: 32, bold: true, color: BRAND.white.replace('#', ''),
    fontFace: 'Arial',
  });

  if (data.capability) {
    titleSlide.addText(`Capability: ${data.capability}`, {
      x: 0.8, y: 3.0, w: 8.4, h: 0.5,
      fontSize: 16, color: BRAND.teal.replace('#', ''),
      fontFace: 'Arial',
    });
  }

  titleSlide.addText([
    { text: `Instance: ${data.instanceName}`, options: { breakLine: true } },
    { text: data.instanceUrl, options: { hyperlink: { url: data.instanceUrl }, color: BRAND.teal.replace('#', ''), breakLine: true } },
    { text: `Date: ${data.scanDate}` },
  ], {
    x: 0.8, y: 3.8, w: 8.4, h: 1.2,
    fontSize: 14, color: BRAND.grayLight.replace('#', ''),
    fontFace: 'Arial',
    lineSpacingMultiple: 1.5,
  });

  titleSlide.addText('Generated by ServiceNow MCP Toolkit', {
    x: 0.8, y: 6.5, w: 8.4, h: 0.4,
    fontSize: 11, color: BRAND.gray.replace('#', ''),
    fontFace: 'Arial',
  });

  // ─── Slide 2: Executive Summary ────────────────────────────────────────
  const summarySlide = pptx.addSlide({ masterName: 'BRANDED' });
  summarySlide.addText('Executive Summary', {
    x: 0.5, y: 0.3, w: 9, h: 0.6,
    fontSize: 24, bold: true, color: BRAND.navy.replace('#', ''),
    fontFace: 'Arial',
  });

  // Health status
  if (data.metrics.overallHealth) {
    const healthColor = data.metrics.overallHealth === 'healthy' ? BRAND.healthy
      : data.metrics.overallHealth === 'degraded' ? BRAND.degraded : BRAND.criticalHealth;
    summarySlide.addText(`Overall Health: ${data.metrics.overallHealth.toUpperCase()}`, {
      x: 0.5, y: 1.0, w: 4, h: 0.4,
      fontSize: 14, bold: true, color: healthColor.replace('#', ''),
      fontFace: 'Arial',
    });
  }

  // Severity count boxes
  const boxWidth = 1.6;
  const boxGap = 0.25;
  const startX = 0.5;
  const boxY = 1.6;

  SEVERITY_ORDER.forEach((sev, i) => {
    const x = startX + i * (boxWidth + boxGap);
    const color = severityColor(sev).replace('#', '');
    summarySlide.addShape('rect', {
      x, y: boxY, w: boxWidth, h: 1.0,
      fill: { color, transparency: 90 },
      line: { color, width: 1.5 },
      rectRadius: 0.05,
    });
    summarySlide.addText(data.metrics.severityCounts[sev].toString(), {
      x, y: boxY + 0.05, w: boxWidth, h: 0.55,
      fontSize: 28, bold: true, color,
      align: 'center', fontFace: 'Arial',
    });
    summarySlide.addText(severityLabel(sev), {
      x, y: boxY + 0.55, w: boxWidth, h: 0.35,
      fontSize: 10, color: BRAND.textLight.replace('#', ''),
      align: 'center', fontFace: 'Arial',
    });
  });

  // Total findings
  summarySlide.addText(`Total Findings: ${data.metrics.totalFindings}`, {
    x: 0.5, y: 2.9, w: 9, h: 0.4,
    fontSize: 14, color: BRAND.text.replace('#', ''),
    fontFace: 'Arial',
  });

  // Executive summary text
  if (data.executiveSummary) {
    summarySlide.addText(data.executiveSummary.slice(0, 600), {
      x: 0.5, y: 3.5, w: 9, h: 3.2,
      fontSize: 12, color: BRAND.textLight.replace('#', ''),
      fontFace: 'Arial',
      valign: 'top',
      lineSpacingMultiple: 1.3,
    });
  }

  // ─── Slide 3: Severity Pie Chart ───────────────────────────────────────
  if (data.metrics.totalFindings > 0) {
    const chartSlide = pptx.addSlide({ masterName: 'BRANDED' });
    chartSlide.addText('Severity Distribution', {
      x: 0.5, y: 0.3, w: 9, h: 0.6,
      fontSize: 24, bold: true, color: BRAND.navy.replace('#', ''),
      fontFace: 'Arial',
    });

    const pieLabels = SEVERITY_ORDER.filter(s => data.metrics.severityCounts[s] > 0);
    const pieValues = pieLabels.map(s => data.metrics.severityCounts[s]);
    const pieColors = pieLabels.map(s => severityColor(s).replace('#', ''));

    if (pieValues.length > 0) {
      chartSlide.addChart('pie', [{ name: 'Findings', labels: pieLabels.map(s => severityLabel(s)), values: pieValues }], {
        x: 0.5, y: 1.2, w: 4.5, h: 4.5,
        showTitle: false,
        showValue: true,
        showPercent: true,
        chartColors: pieColors,
        dataLabelFontSize: 10,
        dataLabelColor: BRAND.text.replace('#', ''),
      });
    }

    // Category breakdown as bar chart
    const catEntries = Object.entries(data.metrics.categoryBreakdown)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 8);

    if (catEntries.length > 0) {
      chartSlide.addChart('bar', [{ name: 'Findings', labels: catEntries.map(e => e[0].slice(0, 20)), values: catEntries.map(e => e[1]) }], {
        x: 5.5, y: 1.2, w: 4.2, h: 4.5,
        showTitle: true,
        title: 'By Category',
        titleFontSize: 12,
        titleColor: BRAND.navy.replace('#', ''),
        chartColors: [BRAND.teal.replace('#', '')],
        showValue: true,
        dataLabelFontSize: 9,
        catAxisLabelFontSize: 9,
        valAxisLabelFontSize: 9,
        barDir: 'bar',
      });
    }
  }

  // ─── Slides 4+: Findings by Section ────────────────────────────────────
  for (const section of data.sections) {
    if (section.findings.length === 0) continue;

    const findingsSlide = pptx.addSlide({ masterName: 'BRANDED' });
    findingsSlide.addText(`${section.title} (${section.findings.length} findings)`, {
      x: 0.5, y: 0.3, w: 9, h: 0.6,
      fontSize: 20, bold: true, color: BRAND.navy.replace('#', ''),
      fontFace: 'Arial',
    });

    // Top findings as table (max 6 per slide)
    const topFindings = section.findings.slice(0, 6);
    const tableRows: any[][] = [
      [
        { text: 'Severity', options: { bold: true, fontSize: 10, color: BRAND.navy.replace('#', ''), fill: { color: BRAND.offWhite.replace('#', '') } } },
        { text: 'Finding', options: { bold: true, fontSize: 10, color: BRAND.navy.replace('#', ''), fill: { color: BRAND.offWhite.replace('#', '') } } },
        { text: 'Impact', options: { bold: true, fontSize: 10, color: BRAND.navy.replace('#', ''), fill: { color: BRAND.offWhite.replace('#', '') } } },
        { text: 'Recommendation', options: { bold: true, fontSize: 10, color: BRAND.navy.replace('#', ''), fill: { color: BRAND.offWhite.replace('#', '') } } },
      ],
    ];

    for (const finding of topFindings) {
      // Build finding cell with evidence and clickable record links
      const findingParts = linkifyTextPptx(finding.title, data.instanceUrl, { fontSize: 9, bold: true, color: BRAND.text.replace('#', '') });
      if (finding.evidence) {
        findingParts.push({ text: '\n', options: { fontSize: 5 } });
        findingParts.push(...linkifyTextPptx(finding.evidence, data.instanceUrl, { fontSize: 7, italic: true, color: BRAND.gray.replace('#', '') }));
      }
      if (finding.table && finding.sysId) {
        const snLink = buildRecordLink(data.instanceUrl, finding.table, finding.sysId);
        findingParts.push({ text: '\nView in ServiceNow', options: { fontSize: 7, color: BRAND.teal.replace('#', ''), underline: true, hyperlink: { url: snLink } } });
      }

      tableRows.push([
        { text: severityLabel(finding.severity), options: { fontSize: 9, bold: true, color: severityColor(finding.severity).replace('#', '') } },
        findingParts,
        linkifyTextPptx(finding.impact || '—', data.instanceUrl, { fontSize: 9, color: BRAND.textLight.replace('#', '') }),
        linkifyTextPptx(finding.recommendation || '—', data.instanceUrl, { fontSize: 9, color: BRAND.text.replace('#', '') }),
      ]);
    }

    findingsSlide.addTable(tableRows, {
      x: 0.3, y: 1.1, w: 9.4,
      border: { type: 'solid', pt: 0.5, color: BRAND.grayLight.replace('#', '') },
      colW: [1.2, 3.0, 2.6, 2.6],
      rowH: 0.6,
      autoPage: false,
    });
  }

  // ─── Recommendations Slide ─────────────────────────────────────────────
  const criticalAndHigh = data.findings.filter(f => f.severity === 'critical' || f.severity === 'high');
  if (criticalAndHigh.length > 0) {
    const recSlide = pptx.addSlide({ masterName: 'BRANDED' });
    recSlide.addText('Priority Recommendations', {
      x: 0.5, y: 0.3, w: 9, h: 0.6,
      fontSize: 24, bold: true, color: BRAND.navy.replace('#', ''),
      fontFace: 'Arial',
    });

    const recParts: any[] = [];
    criticalAndHigh
      .filter(f => f.recommendation)
      .slice(0, 8)
      .forEach((f, i) => {
        const titleLine = `${i + 1}. [${severityLabel(f.severity)}] ${f.title}`;
        const titleParts = linkifyTextPptx(titleLine, data.instanceUrl, {
          fontSize: 11, bold: true, color: BRAND.text.replace('#', ''), breakLine: true,
        });
        recParts.push(...titleParts);
        if (f.recommendation) {
          const recTextParts = linkifyTextPptx(`    ${f.recommendation}`, data.instanceUrl, {
            fontSize: 10, color: BRAND.textLight.replace('#', ''), breakLine: true,
          });
          recParts.push(...recTextParts);
        }
        recParts.push({ text: '\n', options: { fontSize: 6, breakLine: true } });
      });

    if (recParts.length > 0) {
      recSlide.addText(recParts, {
        x: 0.5, y: 1.2, w: 9, h: 5.5,
        fontFace: 'Arial',
        valign: 'top',
      });
    }
  }

  // ─── Closing Slide ─────────────────────────────────────────────────────
  const closingSlide = pptx.addSlide();
  closingSlide.addShape('rect', { x: 0, y: 0, w: '100%', h: '100%', fill: { color: BRAND.navy.replace('#', '') } });
  closingSlide.addShape('rect', { x: 0, y: 7.4, w: '100%', h: 0.1, fill: { color: BRAND.teal.replace('#', '') } });

  closingSlide.addText('ServiceNow MCP Toolkit', {
    x: 0, y: 2.5, w: '100%', h: 1,
    fontSize: 40, bold: true, color: BRAND.white.replace('#', ''),
    align: 'center', fontFace: 'Arial',
  });

  closingSlide.addText('The #1 AI App for ServiceNow', {
    x: 0, y: 3.4, w: '100%', h: 0.6,
    fontSize: 18, color: BRAND.teal.replace('#', ''),
    align: 'center', fontFace: 'Arial',
  });

  closingSlide.addText([
    { text: 'servicenow-mcp.com', options: { hyperlink: { url: 'https://servicenow-mcp.com' }, color: BRAND.teal.replace('#', '') } },
  ], {
    x: 0, y: 4.5, w: '100%', h: 0.5,
    fontSize: 14, align: 'center', fontFace: 'Arial',
  });

  // ─── Write file ────────────────────────────────────────────────────────
  await pptx.writeFile({ fileName: outputPath });

  const stats = statSync(outputPath);
  return { filePath: outputPath, sizeBytes: stats.size };
}
