import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-uib',
  title: 'Build UI Builder Component',
  description:
    'Guided UI Builder component creation — macroponents, data sources, responsive layouts, Next Experience',
  category: 'build',
  arguments: [
    {
      name: 'description',
      description: 'what the component should do in plain language',
      required: true,
    },
    {
      name: 'component_type',
      description: 'page, macroponent, data_resource. Default: macroponent',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_core_records_query',
    'snow_ws_uib_pages_index',
    'snow_ws_uib_page_read',
    'snow_ws_uib_page_add',
    'snow_ws_uib_component_add',
    'snow_ws_uib_components_index',
    'snow_ws_uib_data_brokers_index',
    'snow_ws_uib_data_broker_add',
  ],
  buildPrompt(args = {}) {
    const desc = args.description ?? '<not provided>';
    const componentType = args.component_type ?? 'macroponent';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Build UI Builder Component (Next Experience)',
            '',
            '## UI Builder Architecture — Platform Knowledge',
            '',
            '### Core Concepts',
            '- **UI Builder (UIB):** the declarative page builder for Next Experience (workspace, configurable workspace, app shell). Replaces Service Portal for new development.',
            '- **Next Experience:** ServiceNow\'s modern UI framework built on web components (not AngularJS). Uses the Seismic framework (`@seismic/core`).',
            '- **Now Experience Design System (NEDS):** ServiceNow\'s component library providing consistent, accessible, themeable components (now-button, now-input, now-heading, now-card, now-modal, etc.).',
            '',
            '### Component Hierarchy',
            '- **UX Application:** top-level container that defines a workspace or portal experience. Contains pages and navigation.',
            '- **Page:** a routable view within a UX Application. Composed of layout containers, macroponents, and components.',
            '- **Macroponent:** a composite component that bundles child components, data resources, event handlers, and layout. The primary reusable building block.',
            '- **Component:** a single Now Experience web component (NEDS component or custom). The atomic UI unit.',
            '- **Data Resource:** provides data to components. Types: REST, GraphQL, Script, Transform.',
            '',
            '### Macroponent Architecture',
            '- **Composition:** a macroponent arranges child components in a layout tree. Each child is a reference to a base component (NEDS or custom) with configured properties.',
            '- **Properties:** typed inputs that page designers configure. Types: string, number, boolean, object, array, json, choice, reference, glide_object.',
            '- **Internal state:** managed via `updateState` and `state` in component actions. State is private to the macroponent instance.',
            '- **Data Resources:** bound to properties via data binding expressions. When data changes, bound properties update automatically.',
            '- **Event Handlers:** respond to events dispatched by child components. Can trigger component actions, data resource refreshes, or dispatch events upward.',
            '- **Component Actions:** JavaScript functions that execute logic, update state, or interact with data resources.',
            '',
            '### @seismic/core Framework',
            '- **`createCustomElement`:** defines a custom web component with lifecycle hooks.',
            '- **`dispatch`:** emit custom events from a component to its parent macroponent or page.',
            '- **`updateState`:** update internal component state, triggering a re-render.',
            '- **`actionHandlers`:** define named actions that can be triggered by event handlers in the macroponent.',
            '- **Lifecycle hooks:** `connected` (element added to DOM), `disconnected` (removed from DOM), `propertyChanged` (a property value changed).',
            '- **`state` and `properties`:** state is internal/mutable; properties are external/immutable (set by parent).',
            '',
            '### Data Resources',
            '- **REST:** call a ServiceNow REST API (Table API, Import Set API, custom Scripted REST) or external API. Configure URL, method, headers, query params, body. Supports pagination.',
            '- **GraphQL:** query the ServiceNow GraphQL API for efficient, typed data retrieval. Define query, variables, and field mappings.',
            '- **Script:** server-side GlideRecord/GlideQuery script that returns data. Most flexible, but less cacheable. Runs in a scoped script environment.',
            '- **Transform:** take output from another data resource and transform/filter/map it client-side.',
            '- **Binding:** data resource outputs bind to component properties via `@data.resourceName.output.fieldName`.',
            '- **Refresh triggers:** data resources can be configured to refresh on events, intervals, or page parameter changes.',
            '',
            '### Layout System',
            '- UIB uses a **responsive grid** system with configurable breakpoints.',
            '- Layout containers: `now-container`, `now-row`, `now-col` for grid-based layouts.',
            '- **CSS Grid and Flexbox** are supported via custom CSS on macroponents.',
            '- **Breakpoint-aware properties:** set different property values per breakpoint (mobile, tablet, desktop) for responsive behavior.',
            '- Use **layout variants** to define different compositions for different screen sizes.',
            '',
            '### Theming',
            '- UIB supports **theme inheritance** — components inherit theme variables from the UX Application.',
            '- Use NEDS CSS custom properties (e.g., `--now-color--primary-1`, `--now-font-size--md`) for consistent theming.',
            '- Custom CSS should reference theme variables, not hardcoded values.',
            '- Dark mode support is built-in when using NEDS variables.',
            '',
            '### Accessibility (A11y)',
            '- NEDS components are **WCAG 2.1 AA compliant** out of the box.',
            '- Custom macroponents must maintain accessibility: ARIA roles, labels, live regions, keyboard navigation.',
            '- Use `role`, `aria-label`, `aria-labelledby`, `aria-describedby`, `aria-live` on custom containers.',
            '- Ensure keyboard focus management: `tabindex`, focus trapping in modals, skip navigation links.',
            '- Use semantic HTML structure (headings hierarchy, landmarks).',
            '- Screen reader testing: verify all dynamic content changes are announced.',
            '',
            '### Event System',
            '- Components dispatch events via `dispatch(eventName, payload)`.',
            '- Macroponents handle events via event handler mappings: `event → action`.',
            '- Events can propagate upward: component → macroponent → page → UX App.',
            '- Standard events: `NOW_RECORD#SELECTED`, `NOW_MODAL#OPENED`, `NOW_BUTTON#CLICKED`, etc.',
            '- Custom events: define with clear naming convention `[SCOPE]_[COMPONENT]#[ACTION]`.',
            '',
            '### Performance Considerations',
            '- Minimize data resource calls — use GraphQL for efficient field selection.',
            '- Avoid unnecessary re-renders — use `shouldComponentUpdate` logic in action handlers.',
            '- Lazy-load macroponents that are not immediately visible.',
            '- Use data resource caching (TTL) for infrequently changing data.',
            '- Keep component tree depth shallow for faster rendering.',
            '',
            '---',
            '',
            `Starting UIB component build for: **${desc}**`,
            `Component type: **${componentType}**`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: [
            `Build a UI Builder component for the following requirement:`,
            `**Requirement:** ${desc}`,
            `**Component type:** ${componentType}`,
            '',
            'Follow these steps exactly:',
            '',
            '### Step 1 — Understand the Requirement',
            'Parse the requirement and determine:',
            `- **Component type:** ${componentType}. Validate this is appropriate:`,
            '  - **Page:** a full routable view (list page, record page, dashboard). Use when building a complete screen.',
            '  - **Macroponent:** a reusable composite component (data table with filters, form section, card collection). Use for reusable building blocks.',
            '  - **Data Resource:** a data-fetching component (REST, GraphQL, Script). Use when the primary need is data access logic.',
            '  If the chosen type is not appropriate, recommend the correct type and explain why.',
            '- **Data needs:** what tables/APIs provide the data. Identify data sources and their output shape.',
            '- **User interaction:** what actions the user performs (select, filter, create, edit, navigate, approve).',
            '- **Responsive requirements:** how the component behaves on desktop vs tablet vs mobile.',
            '',
            '### Step 2 — Check Existing UIB Components for Reuse',
            'Use **list_uib_pages** and **list_uib_components** to find existing components with similar functionality:',
            '- Check NEDS components first — many common patterns (tables, forms, cards, modals) already exist.',
            '- Check custom macroponents in the instance for domain-specific components.',
            '- If a suitable component exists, recommend composing with it rather than building from scratch.',
            '',
            '### Step 3 — Design Component Architecture',
            'Plan the full component structure before building:',
            '',
            '```',
            `COMPONENT: [Name] (${componentType})`,
            '  PROPERTIES (configurable inputs):',
            '    - propertyName: type — description (default value)',
            '  ',
            '  DATA RESOURCES:',
            '    - resourceName: [REST|GraphQL|Script]',
            '      Source: [API/table/script details]',
            '      Output shape: { field: type, ... }',
            '      Refresh: [event|interval|manual]',
            '  ',
            '  CHILD COMPONENTS:',
            '    - now-heading: bound to data.title',
            '    - now-card (repeated): bound to data.items[]',
            '    - now-button: dispatches CUSTOM#ACTION',
            '  ',
            '  EVENT HANDLERS:',
            '    - CHILD_EVENT → actionName → [update state | refresh data | dispatch parent event]',
            '  ',
            '  COMPONENT ACTIONS:',
            '    - actionName(payload): [logic description]',
            '  ',
            '  LAYOUT:',
            '    - Desktop: [grid/flex description]',
            '    - Tablet: [adaptations]',
            '    - Mobile: [adaptations]',
            '```',
            '',
            '### Step 4 — Define Data Sources',
            'For each data resource the component needs:',
            '',
            '**REST Data Resource:**',
            '- API endpoint (Table API path, Scripted REST endpoint, or external URL).',
            '- HTTP method, headers, query parameters.',
            '- Request body template (for POST/PUT).',
            '- Response mapping: which fields from the response map to output properties.',
            '- Pagination configuration (limit, offset parameters).',
            '',
            '**GraphQL Data Resource:**',
            '- GraphQL query string with variables.',
            '- Variable bindings from component properties.',
            '- Field selection (only request what the template needs).',
            '',
            '**Script Data Resource:**',
            '- Server-side script using GlideRecord/GlideQuery.',
            '- Input parameters from component properties.',
            '- Output object shape.',
            '- Error handling and fallback data.',
            '',
            'Use **create_uib_data_broker** for each data resource. Bind outputs to component properties using `@data.resourceName.output.fieldName`.',
            '',
            '### Step 5 — Build Responsive Layout',
            'Design the layout for all breakpoints:',
            '',
            '**Desktop (>= 1200px):**',
            '- Full layout with sidebars, multi-column grids.',
            '- All interactive elements visible.',
            '',
            '**Tablet (768px - 1199px):**',
            '- Reduce columns (3-col → 2-col).',
            '- Collapse secondary sidebars into expandable panels.',
            '',
            '**Mobile (< 768px):**',
            '- Single-column stacked layout.',
            '- Collapse complex tables into card lists.',
            '- Touch-friendly tap targets (min 44x44px).',
            '',
            'Use NEDS layout components (`now-container`, `now-row`, `now-col`) with breakpoint-aware properties. Set different values per breakpoint for properties like `columns`, `gap`, `visibility`.',
            '',
            '### Step 6 — Implement Client-Side Logic',
            'Write component actions using @seismic/core patterns:',
            '',
            '**Action Handlers:**',
            '```javascript',
            'actionHandlers: {',
            '  HANDLE_ITEM_CLICK: ({ action, state, updateState, dispatch }) => {',
            '    const { payload } = action;',
            '    updateState({ selectedItem: payload.item });',
            '    dispatch("ITEM_SELECTED", { sys_id: payload.item.sys_id });',
            '  },',
            '  HANDLE_FILTER_CHANGE: ({ action, state, updateState }) => {',
            '    updateState({ filterValue: action.payload.value, page: 1 });',
            '    // Data resource bound to state.filterValue will auto-refresh',
            '  },',
            '  HANDLE_DATA_LOADED: ({ action, updateState }) => {',
            '    updateState({ items: action.payload.result, loading: false });',
            '  },',
            '  HANDLE_ERROR: ({ action, updateState }) => {',
            '    updateState({ error: action.payload.message, loading: false });',
            '  },',
            '}',
            '```',
            '',
            '**Event Handler Mappings (macroponent config):**',
            '- Map child component events to action handlers.',
            '- Map data resource events (success, error) to action handlers.',
            '- Map page-level events (parameter changes, navigation) to action handlers.',
            '',
            '**State Management:**',
            '- Keep state minimal — derive computed values in actions, not state.',
            '- Use `updateState` for batched state updates (single re-render).',
            '- Avoid storing data resource output in state unless transformation is needed.',
            '',
            '### Step 7 — Accessibility Review',
            'Verify the component meets WCAG 2.1 AA:',
            '- **ARIA roles:** containers have appropriate landmark roles (`main`, `navigation`, `region`, `complementary`).',
            '- **ARIA labels:** all interactive elements have `aria-label` or `aria-labelledby`.',
            '- **Keyboard navigation:** all interactive elements are reachable via Tab. Enter/Space activate buttons. Escape closes modals.',
            '- **Focus management:** after data loads or view changes, focus moves to the appropriate element. Modals trap focus.',
            '- **Screen reader:** dynamic content changes use `aria-live="polite"` regions. Loading states are announced.',
            '- **Color contrast:** text meets 4.5:1 contrast ratio against background (NEDS handles this when using theme variables).',
            '- **Heading hierarchy:** use proper heading levels (h1 → h2 → h3) without skipping.',
            '',
            '### Step 8 — Create the Component',
            `Use the appropriate tool to create the ${componentType}:`,
            '',
            componentType === 'page'
              ? [
                  '- Use **create_uib_page** with:',
                  '  - Page title and route path.',
                  '  - Layout definition with containers, rows, columns.',
                  '  - Macroponent/component instances in each layout slot.',
                  '  - Data resource bindings.',
                  '  - Page-level event handlers.',
                ].join('\n')
              : componentType === 'data_resource'
                ? [
                    '- Use **create_uib_data_broker** with:',
                    '  - Resource type (REST, GraphQL, Script).',
                    '  - Configuration (endpoint, query, script).',
                    '  - Input parameter definitions.',
                    '  - Output schema.',
                    '  - Caching and refresh configuration.',
                  ].join('\n')
                : [
                    '- Use **create_uib_component** with:',
                    '  - Macroponent name and description.',
                    '  - Property definitions (name, type, default, description).',
                    '  - Child component composition tree.',
                    '  - Data resource definitions and bindings.',
                    '  - Event handler mappings.',
                    '  - Component actions (JavaScript).',
                    '  - CSS/SCSS for layout and styling.',
                  ].join('\n'),
            '',
            'Report the sys_id of the created component.',
            '',
            'Provide deployment guidance:',
            '1. How to add the component to a UIB page.',
            '2. Which properties need to be configured by the page designer.',
            '3. Which data resources need to be connected.',
            '4. Any workspace or UX App configuration needed.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
