import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-portal',
  title: 'Build Service Portal Widget',
  description:
    'Guided Service Portal widget creation — server script, client controller, HTML template, CSS, data brokers',
  category: 'build',
  arguments: [
    {
      name: 'description',
      description: 'what the widget should do in plain language',
      required: true,
    },
    {
      name: 'widget_name',
      description: 'widget name / ID (e.g., my-custom-widget)',
      required: false,
    },
    {
      name: 'table',
      description: 'primary table the widget interacts with',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_core_records_query',
    'snow_core_table_schema_read',
    'snow_portal_portal_widgets_index',
    'snow_portal_portal_widget_read',
    'snow_portal_portal_widget_add',
    'snow_portal_portal_widget_modify',
  ],
  buildPrompt(args = {}) {
    const desc = args.description ?? '<not provided>';
    const widgetName = args.widget_name ?? '<auto-generate from description>';
    const table = args.table ?? '<not specified>';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Build Service Portal Widget',
            '',
            '## Service Portal Widget Architecture — Platform Knowledge',
            '',
            '### Widget Lifecycle',
            '1. **Server script executes first** (runs on the server as a Rhino script). Sets `data` object properties that are sent to the client.',
            '2. **Client controller executes** (AngularJS 1.x). Receives `data` via `$scope.data` (aliased as `c.data` in the template via `controllerAs: \'c\'`).',
            '3. **HTML template renders** using Angular directives and `c.data` / `c.server` bindings.',
            '4. **CSS/SCSS** styles the widget, scoped to the widget instance.',
            '5. **Client interactions** can call back to the server via `c.server.update()` which re-executes the server script with `input` object containing client-sent data.',
            '',
            '### Server Script Patterns',
            '- **`data` object:** the bridge between server and client. Set `data.myProperty = value` and access it as `c.data.myProperty` in the template.',
            '- **`input` object:** populated when the client calls `c.server.update()`. Check `if (input)` to differentiate initial load from client callbacks.',
            '- **`options` object:** widget instance options configured in the Page Editor.',
            '- **`$sp` API:**',
            '  - `$sp.getParameter(name)` — read URL parameters.',
            '  - `$sp.getPortalRecord()` — get the current portal\'s GlideRecord.',
            '  - `$sp.getUser()` — get current user info (sys_id, name, roles).',
            '  - `$sp.getStream(table, sys_id)` — get activity stream for a record.',
            '  - `$sp.getRecordDisplayValues(data, gr, fields)` — bulk-extract display values.',
            '  - `$sp.getWidget(widgetId, options)` — get embedded widget instance.',
            '  - `$sp.getValues(data, gr, fields)` — bulk-extract raw values.',
            '- **GlideRecord queries:** use standard GlideRecord in server script. Apply `addEncodedQuery()` for complex filters. Always check `canRead()` before exposing data.',
            '- **GlideQuery:** modern alternative — `new GlideQuery(table).where(field, value).select(fields).toArray(limit)`. Cleaner, chainable, but check instance version support.',
            '',
            '### Client Controller Patterns',
            '- **`$scope.data`** (or `c.data`): read-only mirror of server data. Modify `c.data` and call `c.server.update()` to sync back.',
            '- **`c.server.update()`:** sends `c.data` to the server script as `input`. Returns a promise. Use `.then(function(response) { c.data = response.data; })` to handle the response.',
            '- **`c.server.get(params)`:** sends arbitrary params object to the server without merging with `c.data`.',
            '- **`spUtil` service:**',
            '  - `spUtil.update($scope)` — alternative to `c.server.update()` with automatic `$scope.data` binding.',
            '  - `spUtil.get(widgetId, options)` — dynamically load a widget.',
            '  - `spUtil.addInfoMessage(msg)` / `spUtil.addErrorMessage(msg)` — toast notifications.',
            '  - `spUtil.addTrivialMessage(msg)` — subtle notification.',
            '  - `spUtil.recordWatch($scope, table, filter, callback)` — real-time record updates via Ambient Message.',
            '- **`$rootScope.$broadcast` / `$on`:** inter-widget communication. Use custom events (e.g., `$rootScope.$broadcast(\'my-widget.data-changed\', payload)`).',
            '- **`$location` service:** read/manipulate URL for routing within the portal.',
            '- **`$timeout` service:** use instead of `setTimeout` for Angular digest-safe delays.',
            '',
            '### HTML Template Patterns',
            '- **Binding:** use `{{c.data.field}}` for interpolation, `ng-bind="c.data.field"` for safer XSS-free rendering.',
            '- **Lists:** `ng-repeat="item in c.data.items track by item.sys_id"` — always use `track by` for performance.',
            '- **Conditionals:** `ng-if="c.data.showSection"` (removes DOM) vs `ng-show` (hides with CSS).',
            '- **Forms:** `ng-model="c.data.formField"` for two-way binding. Use `ng-submit="c.submitForm()"` on `<form>`.',
            '- **Events:** `ng-click="c.doAction(item)"`, `ng-change="c.onFieldChange()"`, `ng-keypress`.',
            '- **Embedded widgets:** `<sp-widget widget="c.data.embeddedWidget"></sp-widget>`.',
            '- **Accessibility:** always include `aria-label`, `role`, `tabindex` on interactive elements. Use semantic HTML (`<button>`, `<a>`, `<nav>`).',
            '- **Localization:** use `${gs.getMessage("key")}` in server script or `{{::c.data.translatedLabel}}` — never hardcode user-facing strings.',
            '',
            '### CSS/SCSS Patterns',
            '- Widgets get **scoped CSS** — styles apply only within the widget\'s DOM boundary.',
            '- Use **BEM naming:** `.widget-name__element--modifier`.',
            '- Use **ServiceNow SCSS variables:** `$brand-primary`, `$brand-success`, `$brand-danger`, `$text-color`, `$panel-bg`, etc.',
            '- **Responsive breakpoints:** use `@media (max-width: 768px)` for mobile. Portal uses Bootstrap 3 grid (`col-xs-`, `col-sm-`, `col-md-`, `col-lg-`).',
            '- Avoid `!important` — use specificity instead.',
            '- Avoid absolute positioning unless necessary — prefer flexbox.',
            '',
            '### Security Considerations',
            '- **XSS prevention:** ALWAYS use `ng-bind` instead of `{{}}` for user-generated content. Never use `ng-bind-html` with unsanitized data. If HTML rendering is required, sanitize with `$sce.trustAsHtml()` only after server-side sanitization.',
            '- **ACL enforcement:** server script runs with the current user\'s session. GlideRecord queries respect ACLs by default. Do NOT use `GlideRecordSecure` (it is for background scripts, not portal widgets).',
            '- **Input validation:** validate all `input` fields in the server script before processing. Never trust client data.',
            '- **Role checks:** use `gs.hasRole()` in server script, NOT in the client controller (client-side role checks can be bypassed).',
            '- **SQL injection:** always use GlideRecord API methods — never concatenate strings into `addEncodedQuery()`.',
            '',
            '### Widget Options',
            '- Define configurable options (title, table, filter, show/hide sections) so the widget is reusable across pages.',
            '- Access via `options.my_option` in server script.',
            '- Option types: String, Integer, Boolean, Reference, Choice, Field List.',
            '',
            '### Data Brokers',
            '- Alternative to server scripts for data retrieval in newer portal pages.',
            '- Types: Table, REST, Script.',
            '- Advantages: cacheable, shareable between widgets, GraphQL-like field selection.',
            '',
            '---',
            '',
            `Starting widget build for: **${desc}**`,
            widgetName !== '<auto-generate from description>'
              ? `Widget name: **${widgetName}**`
              : 'Widget name: will be generated from requirement',
            table !== '<not specified>'
              ? `Primary table: **${table}**`
              : 'Primary table: to be determined from requirement analysis',
              '',
              'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: [
            `Build a Service Portal widget for the following requirement:`,
            `**Requirement:** ${desc}`,
            `**Widget name:** ${widgetName}`,
            `**Table:** ${table}`,
            '',
            'Follow these steps exactly:',
            '',
            '### Step 1 — Understand the Requirement',
            'Analyze the requirement and determine:',
            '- **Data needs:** what data the widget displays or manipulates. Which table(s) and fields are involved.',
            '- **User interaction:** what actions can the user perform (view, filter, create, edit, submit, approve).',
            '- **Target users:** who uses this widget (end users, fulfillers, managers). This affects data scoping and ACL considerations.',
            table !== '<not specified>'
              ? `- **Table:** ${table}. Use **get_table_schema** to understand its fields, types, and reference relationships.`
              : '- **Table:** determine the correct table(s). Use **get_table_schema** to verify.',
            '- **Widget context:** where will this widget live (main content, sidebar, modal, embedded in another widget).',
            '',
            '### Step 2 — Check Existing Widgets for Reuse',
            'Use **list_portal_widgets** to find widgets with similar functionality. For each candidate:',
            '- Review its server script, client controller, and template.',
            '- Assess whether it can be reused directly, extended via options, or used as a starting template.',
            '- If a suitable widget exists, recommend using or cloning it instead of building from scratch.',
            '',
            '### Step 3 — Design Widget Architecture',
            'Plan the widget structure before coding:',
            '',
            '```',
            `WIDGET: ${widgetName !== '<auto-generate from description>' ? widgetName : '[generated-name]'}`,
            '  SERVER SCRIPT:',
            '    - data.xxx = [description of each data property]',
            '    - input handling: [what client callbacks are supported]',
            '  CLIENT CONTROLLER:',
            '    - c.methodName() — [description of each method]',
            '    - $scope.$on events — [inter-widget communication]',
            '  HTML TEMPLATE:',
            '    - [layout description: header, body, footer]',
            '    - [list of Angular directives used]',
            '  CSS:',
            '    - [responsive behavior]',
            '    - [key style patterns]',
            '  OPTIONS:',
            '    - [configurable options for reusability]',
            '```',
            '',
            '### Step 4 — Generate Server Script',
            'Write the server script following these requirements:',
            '- Set all `data` properties needed by the template.',
            '- Handle `input` callbacks from the client (check `if (input && input.action === "xxx")`).',
            '- Use `$sp` API for portal-specific operations.',
            '- Apply GlideRecord queries with proper encoded queries and field limits (`.setLimit()`, `.chooseWindow()` for pagination).',
            '- Check `gs.hasRole()` for any role-gated data.',
            '- Call `canRead()` on GlideRecords before exposing sensitive data.',
            '- Include JSDoc-style comments explaining each data property and input handler.',
            '- For embedded widgets, use `data.embeddedWidget = $sp.getWidget("widget-id", options)`.',
            '',
            '### Step 5 — Generate Client Controller',
            'Write the AngularJS client controller:',
            '- Inject only needed services: `$scope`, `spUtil`, `$location`, `$timeout`, `$rootScope`.',
            '- Define `c.server.update()` calls for each client-to-server action.',
            '- Use `.then()` promises on all async operations.',
            '- Implement `spUtil.recordWatch()` if real-time updates are needed.',
            '- Broadcast/listen for inter-widget events with `$rootScope.$broadcast` / `$scope.$on`.',
            '- Handle loading states: set `c.data.loading = true` before server calls, `false` in `.then()`.',
            '- Avoid direct DOM manipulation — use Angular directives and `c.data` bindings.',
            '',
            '### Step 6 — Generate HTML Template',
            'Write the Angular HTML template:',
            '- Use `ng-bind` instead of `{{}}` for user-generated content (XSS prevention).',
            '- Include `track by` on all `ng-repeat` directives.',
            '- Use semantic HTML elements (`<section>`, `<article>`, `<nav>`, `<button>`).',
            '- Add ARIA attributes on interactive elements: `aria-label`, `aria-expanded`, `aria-live` for dynamic regions.',
            '- Support keyboard navigation: `tabindex`, `ng-keypress` for keyboard-accessible actions.',
            '- Use Bootstrap 3 grid classes for responsive layout: `col-xs-12 col-sm-6 col-md-4`.',
            '- Show loading spinner during async operations: `<div ng-if="c.data.loading"><i class="fa fa-spinner fa-spin"></i></div>`.',
            '- Include empty-state messaging when no data is returned.',
            '',
            '### Step 7 — Generate SCSS',
            'Write the SCSS styles:',
            '- Follow BEM naming: `.widget-name__element--modifier`.',
            '- Use ServiceNow SCSS variables (`$brand-primary`, `$text-color`, `$panel-bg`) for theme consistency.',
            '- Implement responsive design with media queries.',
            '- Use flexbox for layout alignment.',
            '- Avoid inline styles in the template — use CSS classes.',
            '- Add hover/focus states for interactive elements.',
            '- Keep specificity low — avoid `!important` and deep nesting.',
            '',
            '### Step 8 — Security Review',
            'Audit the generated widget for security issues:',
            '- **XSS:** verify no unsanitized user input is rendered via `ng-bind-html` or `{{}}`. All user-generated content uses `ng-bind`.',
            '- **ACL bypass:** verify server script does not use `setWorkflow(false)` or bypass ACLs. All GlideRecord queries run with the user\'s session.',
            '- **Input validation:** verify all `input` fields from client callbacks are validated in the server script (type, length, allowed values).',
            '- **CSRF:** `c.server.update()` includes CSRF token automatically via the platform. No manual CSRF handling needed.',
            '- **Data exposure:** verify the server script does not send more data than the template needs (don\'t send entire GlideRecord objects).',
            '- **Role gates:** verify sensitive actions check `gs.hasRole()` in the server script, not just in the client.',
            '',
            '### Step 9 — Create the Widget',
            'Use **create_portal_widget** with:',
            '- Widget ID (kebab-case, descriptive).',
            '- Display name.',
            '- Server script, client controller, HTML template, and CSS.',
            '- Widget options schema if applicable.',
            '',
            'Report the sys_id of the created widget.',
            '',
            'Provide a summary of how to add the widget to a portal page:',
            '1. Navigate to Service Portal > Pages.',
            '2. Open the target page in Page Editor.',
            '3. Add a container/row/column if needed.',
            '4. Drag the widget into the column.',
            '5. Configure widget options in the instance editor.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
