import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-catalog',
  title: 'Build Catalog Item',
  description:
    'End-to-end catalog item creation — variables, UI policies, client scripts, approval rules, fulfillment workflow',
  category: 'build',
  arguments: [
    {
      name: 'description',
      description: 'what the catalog item should provide / what users are requesting',
      required: true,
    },
    {
      name: 'category',
      description: 'catalog category (e.g., Hardware, Software, Access, Services)',
      required: false,
    },
    {
      name: 'fulfillment_type',
      description: 'flow, workflow, approval_only. Default: flow',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_core_records_query',
    'snow_cat_catalog_items_index',
    'snow_cat_catalog_item_read',
    'snow_cat_catalog_item_add',
    'snow_cat_catalog_variable_add',
    'snow_cat_catalog_ui_policy_add',
    'snow_cat_approval_rule_add',
    'snow_flow_flow_add',
    'snow_core_table_schema_read',
  ],
  buildPrompt(args = {}) {
    const desc = args.description ?? '<not provided>';
    const category = args.category ?? '<not specified>';
    const fulfillmentType = args.fulfillment_type ?? 'flow';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Build Catalog Item',
            '',
            '## ServiceNow Service Catalog — Platform Knowledge',
            '',
            '### Catalog Item Architecture',
            '- **Catalog Item** (`sc_cat_item`): the requestable service. Contains metadata (name, description, category, price, picture), variables, workflows, and policies.',
            '- **Category** (`sc_category`): organizational hierarchy for catalog items. Supports nesting (parent → child categories).',
            '- **Variables** (`item_option_new`): form fields on the catalog item. Typed, ordered, and can be mandatory/optional.',
            '- **Variable Sets** (`item_option_new_set`): reusable groups of variables shared across multiple catalog items.',
            '- **Catalog Client Scripts** (`catalog_script_client`): JavaScript that runs on the catalog form (onChange, onLoad, onSubmit). Separate from standard client scripts.',
            '- **Catalog UI Policies** (`catalog_ui_policy`): declarative show/hide/mandatory/read-only rules for catalog variables.',
            '- **Approval Rules** or flows that govern the approval process.',
            '- **Fulfillment** via Flow Designer, Legacy Workflow, or manual task creation.',
            '',
            '### Request Model (REQ / RITM / TASK)',
            '- **Request (REQ)** (`sc_request`): the parent container for one or more ordered items. Created when the user submits the cart.',
            '- **Requested Item (RITM)** (`sc_req_item`): one per catalog item ordered. Contains the variable values the user submitted. Tracks fulfillment state.',
            '- **Catalog Task (SCTASK)** (`sc_task`): sub-tasks under a RITM for fulfillment steps (e.g., "Provision Access", "Ship Hardware"). Assigned to fulfillment groups.',
            '- **Execution Plan:** defines the task sequence for fulfillment — parallel, sequential, or conditional task generation.',
            '',
            '### Variable Types',
            '- **Single Line Text:** free-text input. Max length configurable. Supports regex validation.',
            '- **Multi Line Text:** textarea for longer input.',
            '- **Select Box (Choice):** dropdown with predefined choices. Choices defined inline or from a choice table.',
            '- **Lookup Select Box:** dropdown with choices from a GlideRecord query (filtered, dynamic).',
            '- **Reference:** reference to a record on another table (e.g., sys_user, cmdb_ci). Supports reference qualifiers.',
            '- **Checkbox:** boolean true/false.',
            '- **CheckBox (Yes/No):** explicit Yes/No label checkboxes.',
            '- **Date / Date-Time:** date picker with configurable format.',
            '- **Email / URL / IP Address:** text with built-in format validation.',
            '- **Numeric Scale:** slider or numeric input with min/max/step.',
            '- **Masked:** password-style masked input for sensitive data.',
            '- **List Collector:** multi-select from a reference table (e.g., select multiple users).',
            '- **Multi-Row Variable Set (MRVS):** table-like input where users add multiple rows of structured data (e.g., multiple software titles, multiple users). Each row has its own variables.',
            '- **Container Start / Container End / Container Split:** layout controls for grouping variables visually.',
            '- **Label / Break / Macro:** display-only elements for instructions, spacing, or custom UI.',
            '',
            '### Variable Attributes',
            '- `ref_qual_elements`: reference qualifier for Reference variables (JavaScript function or encoded query).',
            '- `max_length`: character limit for text fields.',
            '- `default_value`: pre-populated value.',
            '- `tooltip`: help text shown on hover.',
            '- `read_only`: prevents user modification.',
            '- `hidden`: hides the variable (still submitted).',
            '- `mandatory`: requires a value before submission.',
            '- `order`: display order (lower = higher on form).',
            '- `question_text`: the label shown to the user.',
            '- `help_text`: additional guidance shown in a help popover.',
            '',
            '### Catalog Client Script Patterns',
            '- **onChange:** `function onChange(control, oldValue, newValue, isLoading) { ... }`. Trigger field specified in script configuration.',
            '- **onLoad:** `function onLoad() { ... }`. Runs when the catalog form loads.',
            '- **onSubmit:** `function onSubmit() { ... return true; }`. Return `false` to prevent submission.',
            '- Use `g_form.getControl(variableName)` to access DOM elements of catalog variables.',
            '- Use `g_form.setValue(variableName, value)` / `g_form.getValue(variableName)` for variable values.',
            '- Use `g_form.setDisplay(variableName, true/false)` to show/hide variables programmatically.',
            '- Use `g_form.setMandatory(variableName, true/false)` for dynamic mandatory rules.',
            '- Use GlideAjax for server-side lookups (same pattern as standard client scripts but targeting catalog Script Includes).',
            '',
            '### Approval Engines',
            '- **Approval Rules** (`sysapproval_approver`): condition-based rules that create approval records. Conditions based on RITM field values.',
            '- **Approval Group:** set an approval group on the catalog item — all members must approve (or configure "anyone").',
            '- **Manager Approval:** use `requested_for.manager` to route to the requester\'s manager.',
            '- **Multi-Level Approval:** chain approval rules (Level 1 → Level 2) using "approval for" relationships or flow-based approval sequences.',
            '- **Auto-Approve:** skip approval for certain roles or dollar thresholds using conditions.',
            '- **Rejection Handling:** define what happens on rejection — cancel RITM, notify requester, allow resubmission.',
            '',
            '### Fulfillment Options',
            '- **Flow Designer (recommended):** create a flow triggered by RITM creation/approval. Use flow actions to create tasks, send notifications, provision resources. Supports error handling, subflows, approval steps.',
            '- **Legacy Workflow:** older visual workflow engine. Still functional but being replaced by Flow Designer.',
            '- **Execution Plan:** define catalog tasks with assignment rules, SLA, and sequencing. Simpler than flows for basic task-based fulfillment.',
            '- **Approval Only:** no fulfillment automation — after approval, the RITM is manually handled by fulfillment groups.',
            '',
            '### Pricing & Cost',
            '- `price`: the price shown to the user (informational or chargeback).',
            '- `recurring_price`: for subscription-style items.',
            '- `cost`: internal cost (not shown to users). Used for budgeting.',
            '- Variables can contribute to dynamic pricing via `price_if_checked` attribute.',
            '',
            '---',
            '',
            `Starting catalog item build for: **${desc}**`,
            category !== '<not specified>'
              ? `Category: **${category}**`
              : 'Category: to be determined from requirement analysis',
            `Fulfillment type: **${fulfillmentType}**`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: [
            `Build an end-to-end catalog item for the following requirement:`,
            `**Requirement:** ${desc}`,
            `**Category:** ${category}`,
            `**Fulfillment type:** ${fulfillmentType}`,
            '',
            'Follow these steps exactly:',
            '',
            '### Step 1 — Understand the Requirement',
            'Analyze the requirement and determine:',
            '- **What service** is being offered — what does the end user receive when the request is fulfilled.',
            '- **Who can request** — all users, specific roles, specific departments, specific locations.',
            '- **What data is needed** — what information must the requester provide (justification, manager approval, asset selection, etc.).',
            '- **Approval path** — who approves and under what conditions. Is auto-approval possible for certain scenarios.',
            '- **Fulfillment steps** — what actions are performed after approval (provision access, ship hardware, create account, assign license).',
            '- **SLA expectations** — how quickly should the request be fulfilled.',
            category !== '<not specified>'
              ? `- **Category:** ${category}. Verify this category exists using **query_records** on sc_category.`
              : '- **Category:** determine the appropriate category. Use **query_records** on sc_category to find existing categories.',
            '',
            '### Step 2 — Check Existing Catalog Items',
            'Use **list_catalog_items** to find similar items:',
            '- Items with similar names or descriptions.',
            '- Items in the same category that might overlap.',
            '- Items that could be extended or cloned instead of building from scratch.',
            '- Variable sets that are already shared across items and could be reused.',
            '',
            'If a very similar item exists, recommend whether to modify it, clone it, or create a new one.',
            '',
            '### Step 3 — Design Variable Layout',
            'Plan all variables the catalog form needs:',
            '',
            '```',
            'CATALOG ITEM: [Name]',
            '  VARIABLES:',
            '    --- Container: "Request Details" ---',
            '    1. variable_name (Type) [mandatory?] — description',
            '       Attributes: default, ref_qual, tooltip',
            '    2. ...',
            '    --- Container End ---',
            '    ',
            '    --- Variable Set: "Common Fields" (reuse existing if available) ---',
            '    3. ...',
            '    --- Variable Set End ---',
            '    ',
            '    --- MRVS: "Items" (if multi-row needed) ---',
            '    4. row_field_1 (Type) — description',
            '    5. row_field_2 (Type) — description',
            '    --- MRVS End ---',
            '```',
            '',
            'For each variable, specify:',
            '- **Name:** snake_case, descriptive.',
            '- **Question text:** user-facing label.',
            '- **Type:** Single Line Text, Select Box, Reference, Checkbox, Date, MRVS, etc.',
            '- **Mandatory:** yes/no (consider making fields conditionally mandatory via UI policies).',
            '- **Order:** display order (use increments of 100 for easy insertion).',
            '- **Default value:** pre-populate if appropriate.',
            '- **Help text / Tooltip:** guidance for the requester.',
            '- **Reference qualifier:** for Reference variables, define the filter (e.g., "active=true^department=IT").',
            '- **Validation:** regex pattern for text fields, min/max for numeric fields.',
            '',
            'Use **create_catalog_variable** for each variable.',
            '',
            '### Step 4 — Create UI Policies',
            'Define declarative rules for dynamic form behavior:',
            '',
            'For each UI policy, specify:',
            '- **Condition:** when the policy applies (e.g., `variable_type == "Hardware"`).',
            '- **Actions:** show/hide, mandatory/not mandatory, read-only/editable for target variables.',
            '- **Reverse if false:** whether to reverse the actions when the condition is no longer met.',
            '- **On load:** whether to evaluate on initial form load.',
            '',
            'Common patterns:',
            '- Show additional fields when a category or type is selected.',
            '- Make justification mandatory when cost exceeds a threshold.',
            '- Hide approval-related fields from non-approver users.',
            '- Show/hide MRVS based on a checkbox or select value.',
            '',
            'Use **create_catalog_ui_policy** for each policy.',
            '',
            '### Step 5 — Create Catalog Client Scripts',
            'For dynamic behavior that UI policies cannot express:',
            '',
            '**onChange scripts:**',
            '- Populate dependent fields based on a selection (e.g., selecting a CI populates its location and support group).',
            '- Calculate estimated cost based on variable selections.',
            '- Dynamic reference qualifier updates.',
            '- Use GlideAjax for server-side lookups (do NOT use synchronous GlideRecord on the client).',
            '',
            '**onLoad scripts:**',
            '- Pre-populate variables from URL parameters or user profile.',
            '- Set dynamic defaults based on the requester\'s department, location, or role.',
            '- Initialize complex variable interactions.',
            '',
            '**onSubmit scripts:**',
            '- Client-side validation that is too complex for UI policies (cross-variable validation, date range checks).',
            '- Confirmation dialogs for high-impact requests.',
            '- Always back up client validation with server-side validation (client scripts can be bypassed).',
            '',
            'For each script, generate the code and use the appropriate creation tool. If GlideAjax is needed, create the corresponding client-callable Script Include.',
            '',
            '### Step 6 — Design Approval Workflow',
            'Define the approval chain based on the requirement:',
            '',
            '**Approval Design:**',
            '- **Level 1:** [who approves] — [condition for this level].',
            '- **Level 2 (if needed):** [who approves] — [condition].',
            '- **Auto-approve conditions:** [when approval is skipped].',
            '- **Rejection handling:** [what happens when rejected — cancel, allow resubmission, notify].',
            '- **Escalation:** [what happens if approval is not acted on within SLA — remind, escalate to manager\'s manager].',
            '',
            'Common approval patterns:',
            '- **Manager approval:** route to `requested_for.manager`. Simple, works for most HR/IT requests.',
            '- **Group approval:** route to a specific group (e.g., "IT Security Approvers"). Use when specialized knowledge is needed.',
            '- **Cost-based:** auto-approve below $X, manager approval $X-$Y, VP approval above $Y.',
            '- **Role-based bypass:** users with `catalog_admin` role skip approval.',
            '',
            'Use **create_approval_rule** for each approval level.',
            '',
            '### Step 7 — Create Fulfillment Flow',
            `Fulfillment type: **${fulfillmentType}**.`,
            '',
            fulfillmentType === 'flow'
              ? [
                  'Create a Flow Designer flow triggered by RITM approval:',
                  '',
                  '1. **Trigger:** Record update on `sc_req_item` when `approval = approved` and `stage = waiting_for_approval → fulfillment`.',
                  '2. **Read variables:** extract variable values from the RITM for use in fulfillment actions.',
                  '3. **Create fulfillment tasks (SCTASK):**',
                  '   - One task per fulfillment step (e.g., "Provision Account", "Ship Hardware", "Configure Software").',
                  '   - Assign to appropriate fulfillment groups.',
                  '   - Set SLA on each task.',
                  '   - Include variable values in task description for fulfiller reference.',
                  '4. **Send notifications:**',
                  '   - Notify requester that their request is being fulfilled.',
                  '   - Notify fulfillers of new tasks.',
                  '5. **Completion logic:**',
                  '   - When all tasks are closed, close the RITM.',
                  '   - Send fulfillment confirmation to requester.',
                  '6. **Error handling:**',
                  '   - Try/catch around provisioning steps.',
                  '   - On failure: notify support, update RITM work notes, do NOT close the RITM.',
                  '',
                  'Use **create_flow** to build the fulfillment flow.',
                ].join('\n')
              : fulfillmentType === 'workflow'
                ? [
                    'Design a legacy workflow for fulfillment:',
                    '',
                    '- Triggered on RITM approval.',
                    '- Create catalog tasks with assignment rules.',
                    '- Include approval activities if multi-stage approval is needed.',
                    '- Add notification activities for requester and fulfillers.',
                    '- Include error handling with "Run Script" activities for complex logic.',
                    '',
                    'Note: Flow Designer is recommended for new development. Consider using Flow Designer instead.',
                  ].join('\n')
                : [
                    'No automated fulfillment — approval only:',
                    '',
                    '- After approval, the RITM moves to "Open" state for manual handling.',
                    '- Ensure the RITM assignment group is set so fulfillers know to pick it up.',
                    '- Add a notification to alert the fulfillment group when a new approved RITM is ready.',
                  ].join('\n'),
            '',
            '### Step 8 — Create the Catalog Item',
            'Use **create_catalog_item** with:',
            '- Name, description, short description.',
            '- Category assignment.',
            '- Price (if applicable).',
            '- Availability (active, visible on portal).',
            '- Icon/picture.',
            '- All variables, UI policies, and client scripts linked.',
            '- Fulfillment flow/workflow associated.',
            '',
            'Report the sys_id of the created catalog item and all associated artifacts:',
            '',
            '| Artifact | Type | sys_id | Name |',
            '|----------|------|--------|------|',
            '| Catalog Item | sc_cat_item | ... | ... |',
            '| Variable 1 | item_option_new | ... | ... |',
            '| Variable 2 | item_option_new | ... | ... |',
            '| UI Policy 1 | catalog_ui_policy | ... | ... |',
            '| Client Script 1 | catalog_script_client | ... | ... |',
            '| Approval Rule | sysapproval_approver | ... | ... |',
            '| Fulfillment Flow | sys_hub_flow | ... | ... |',
            '',
            '### Step 9 — Suggest Test Scenarios',
            'Provide a comprehensive test matrix covering the full request lifecycle:',
            '',
            '| # | Scenario | Setup | Steps | Expected Result |',
            '|---|----------|-------|-------|-----------------|',
            '',
            'Include at minimum:',
            '- **Order happy path:** user opens catalog → fills variables → submits → approval requested → approved → tasks created → tasks completed → RITM closed → user notified.',
            '- **Variable validation:** submit with missing mandatory fields, invalid formats, boundary values. Verify error messages are shown.',
            '- **UI policy behavior:** change variable values to trigger each UI policy. Verify show/hide/mandatory/read-only states change correctly.',
            '- **Client script behavior:** trigger each onChange/onLoad/onSubmit script. Verify GlideAjax lookups return correct data.',
            '- **Approval path:** test with different requesters (different managers) and different variable values (different cost tiers) to verify routing.',
            '- **Rejection path:** approve at level 1, reject at level 2 (if multi-level). Verify RITM state, requester notification, and resubmission flow.',
            '- **Fulfillment:** verify each catalog task is created with correct assignment, description, and SLA.',
            '- **Task completion:** close all tasks and verify RITM auto-closes with correct state.',
            '- **Error path:** simulate fulfillment failure. Verify error handling, notifications, and RITM state.',
            '- **Role-based access:** verify the catalog item is visible only to authorized users/roles.',
            '- **Portal rendering:** verify the catalog item renders correctly in Service Portal (variable layout, UI policies, client scripts).',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
