import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-client-script',
  title: 'Build Client Script',
  description:
    'Guided client script creation — onChange, onLoad, onSubmit with g_form/g_user best practices and GlideAjax patterns',
  category: 'build',
  arguments: [
    {
      name: 'description',
      description: 'what the client script should do',
      required: true,
    },
    {
      name: 'table',
      description: 'target table',
      required: true,
    },
    {
      name: 'type',
      description: 'onChange, onLoad, onSubmit, onCellEdit. Default: onChange',
      required: false,
    },
    {
      name: 'field',
      description: 'field name for onChange scripts',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_scr_client_script_add',
    'snow_scr_client_scripts_index',
    'snow_scr_client_script_read',
    'snow_scr_ui_policy_add',
    'snow_core_table_schema_read',
    'snow_scr_script_include_add',
  ],
  buildPrompt(args = {}) {
    const desc = args.description ?? '<not provided>';
    const table = args.table ?? '<not provided>';
    const type = args.type ?? 'onChange';
    const field = args.field ?? '<none specified>';

    return [
      {
        role: 'user',
        content: {
          type: 'text',
          text: [
            `Build a client script for the **${table}** table.`,
            `**Type:** ${type}`,
            `**Field:** ${field}`,
            `**Requirement:** ${desc}`,
            '',
            'Follow these steps exactly:',
            '',
            '### Step 1 — Decide: UI Policy vs Client Script',
            'Evaluate whether the requirement can be met with a **UI Policy** instead of a client script. Use a UI Policy if the behavior is purely:',
            '- Show / hide a field',
            '- Make a field mandatory / not mandatory',
            '- Make a field read-only / editable',
            '- Set a field value based on a simple condition',
            '',
            'If a UI Policy is sufficient, recommend that approach and use **create_ui_policy** instead. Explain the trade-offs (UI Policies are declarative, easier to maintain, and do not require scripting). Only proceed with a client script if the requirement involves complex logic, GlideAjax calls, or dynamic behavior that UI Policies cannot express.',
            '',
            '### Step 2 — Check Existing Client Scripts on the Table',
            `Use **list_client_scripts** filtered to table="${table}". Summarize active scripts in a table (name, type, field, order, description). Flag any that overlap with the new requirement or that run on the same field/event. Identify potential ordering conflicts.`,
            '',
            '### Step 3 — Check Table Schema',
            `Use **get_table_schema** for "${table}". Verify every field name used in the requirement exists. Note field types (reference fields need special handling with getDisplayValue/getReference). If the field argument is set to "${field}", confirm it exists and note its type.`,
            '',
            '### Step 4 — Generate the Script',
            `Generate the client script with the correct function signature for type **${type}**:`,
            '',
            '**onChange:**',
            '```javascript',
            'function onChange(control, oldValue, newValue, isLoading, isTemplate) {',
            '    if (isLoading || newValue === \'\') return;',
            '    // logic here',
            '}',
            '```',
            '',
            '**onLoad:**',
            '```javascript',
            'function onLoad() {',
            '    // logic here',
            '}',
            '```',
            '',
            '**onSubmit:**',
            '```javascript',
            'function onSubmit() {',
            '    // return false to abort submission',
            '    // logic here',
            '    return true;',
            '}',
            '```',
            '',
            '**onCellEdit:**',
            '```javascript',
            'function onCellEdit(sysIDs, table, oldValues, newValue, callback) {',
            '    // callback invocation is required',
            '    callback();',
            '}',
            '```',
            '',
            'Apply these best practices:',
            '- Always check `isLoading` and `isTemplate` in onChange to avoid running on form load.',
            '- Use `g_form.getReference(field, callback)` (async) instead of synchronous GlideRecord on the client.',
            '- Prefer `g_form.setValue()`, `g_form.setDisplay()`, `g_form.setMandatory()`, `g_form.setReadOnly()`.',
            '- Use `g_user.hasRole()` for client-side role checks (but never trust these for security).',
            '- Minimize DOM manipulation — use g_form APIs exclusively.',
            '- Include a JSDoc comment block: purpose, author, date.',
            '',
            '### Step 5 — GlideAjax Pattern (if needed)',
            'If the client script needs server-side data, generate a **GlideAjax** call AND the corresponding **Script Include**:',
            '',
            '**Client side:**',
            '```javascript',
            'var ga = new GlideAjax(\'MyScriptInclude\');',
            'ga.addParam(\'sysparm_name\', \'myMethod\');',
            'ga.addParam(\'sysparm_my_param\', value);',
            'ga.getXMLAnswer(function(answer) {',
            '    // handle response',
            '});',
            '```',
            '',
            '**Script Include (client-callable):**',
            '```javascript',
            'var MyScriptInclude = Class.create();',
            'MyScriptInclude.prototype = Object.extendsObject(AbstractAjaxProcessor, {',
            '    myMethod: function() {',
            '        var param = this.getParameter(\'sysparm_my_param\');',
            '        // server logic, return result',
            '        return JSON.stringify(result);',
            '    },',
            '    type: \'MyScriptInclude\'',
            '});',
            '```',
            '',
            'Use **create_script_include** to create it with `client_callable: true`. Report both artifacts.',
            '',
            '### Step 6 — Review for Security & Quality',
            'Audit the generated script:',
            '- **XSS:** Never inject unsanitized user input into DOM or g_form display values.',
            '- **Client-only validation is insufficient:** If onSubmit validates data, ensure a corresponding server-side business rule also validates (client scripts can be bypassed via API/import).',
            '- **Performance:** Avoid synchronous GlideRecord, excessive GlideAjax calls, or heavy DOM queries.',
            '- **Scoping:** Ensure the script works in both standard and workspace/agent views if applicable.',
            '- **Mobile:** Note if the script will NOT work on mobile/service portal (client scripts are form-view only).',
            '',
            '### Step 7 — Create the Artifact(s)',
            `Use **create_client_script** with the final script, table="${table}", type="${type}"${type === 'onChange' ? `, field="${field}"` : ''}. If a Script Include was generated in Step 5, create it as well. Report the sys_id(s) of all created artifacts.`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
