import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-flow',
  title: 'Build Flow',
  description:
    'Guided Flow Designer creation — triggers, actions, subflows, error handling, testing',
  category: 'build',
  arguments: [
    {
      name: 'description',
      description: 'what the flow should do in plain language',
      required: true,
    },
    {
      name: 'trigger_type',
      description:
        'record, scheduled, application, inbound_email. Default: record',
      required: false,
    },
    {
      name: 'table',
      description: 'target table for record-triggered flows',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_core_records_query',
    'snow_flow_flows_index',
    'snow_flow_flow_read',
    'snow_flow_flow_trigger',
    'snow_flow_flow_add',
    'snow_flow_subflow_add',
    'snow_scr_business_rules_index',
    'snow_core_table_schema_read',
  ],
  buildPrompt(args = {}) {
    const desc = args.description ?? '<not provided>';
    const triggerType = args.trigger_type ?? 'record';
    const table = args.table ?? '<not specified>';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Build Flow (Flow Designer)',
            '',
            '## ServiceNow Flow Designer — Platform Knowledge',
            '',
            '### Trigger Types',
            '- **Record:** fires on insert, update, or delete of a record on a specific table. Supports conditions (e.g., state changes to "Resolved"). Most common trigger type.',
            '- **Scheduled:** fires on a cron schedule (daily, weekly, custom). Used for batch processing, cleanup, periodic sync. Runs as the flow owner unless impersonation is configured.',
            '- **Application:** fires from a Script Action, Business Rule, or another flow via `sn_fd.FlowAPI.startFlow()`. Best for event-driven or decoupled architectures.',
            '- **Inbound Email:** fires when an email is received matching criteria (sender, subject regex, body contains). Used for email-to-ticket, approval via email.',
            '- **REST:** fires from an inbound REST API call. Useful for external system integrations, webhooks.',
            '',
            '### Action Types',
            '- **Create Record / Update Record / Delete Record:** CRUD operations on any table. Use dot-walking for reference field data.',
            '- **Look Up Records / Look Up Record:** query one or many records with conditions. Returns data pills for downstream use.',
            '- **Run Script:** inline server-side JavaScript. Has access to `fd_data` (flow data pills). Use sparingly — prefer built-in actions for maintainability.',
            '- **Call Subflow:** invoke a reusable subflow with input parameters. Outputs from the subflow are available as data pills.',
            '- **Send Notification:** fire a notification with dynamic recipients, subject, and body.',
            '- **Log:** write to sys_log for debugging and audit trail. Include flow context in log messages.',
            '- **If / Else If / Else:** conditional branching based on data pill values, record conditions, or script results.',
            '- **For Each:** iterate over a list of records returned from Look Up Records.',
            '- **Wait For:** pause flow execution until a condition is met (record update, duration elapsed, specific date/time). Creates a `wf_context` record.',
            '- **Ask for Approval:** request approval from users/groups with configurable approval rules (anyone, everyone, percentage).',
            '- **Make REST Call:** outbound HTTP request with dynamic URL, headers, body. Supports OAuth, Basic Auth, mutual TLS.',
            '- **Transform:** data transformation and mapping between data pills.',
            '',
            '### Error Handling Patterns',
            '- **Try / Catch:** wrap risky actions in a try block. The catch block receives error details (message, action that failed). Always include a catch for external calls (REST, Script).',
            '- **Rollback Actions:** in the catch block, undo partially completed work (delete created records, revert field changes).',
            '- **Error Output:** flows can define error outputs so callers (parent flows, subflows) can handle failures gracefully.',
            '- **Logging in Catch:** always log the error with full context (flow name, trigger record, action name, error message) for troubleshooting.',
            '- **Retry Pattern:** for transient failures (REST timeout, lock contention), implement retry with a Wait action followed by re-execution of the failed action.',
            '',
            '### Flow Variables & Data Pills',
            '- **Trigger data pills:** `Trigger Record` and its fields are available as data pills throughout the flow.',
            '- **Action outputs:** each action produces output data pills (created record sys_id, lookup results, script return values).',
            '- **Flow variables:** define typed inputs/outputs on the flow for parameterization. Inputs can be set by callers (Application trigger, parent flow).',
            '- **Inline scripts** access data pills via the `fd_data` object.',
            '- **Dot-walking:** reference field data pills support dot-walking (e.g., `Trigger Record.assigned_to.manager.email`).',
            '',
            '### Subflow Design Principles',
            '- Extract reusable logic into subflows: notification patterns, approval chains, record creation templates.',
            '- Subflows have typed inputs and outputs — define them clearly for reuse.',
            '- Subflows can be called from any flow, reducing duplication.',
            '- Keep subflows focused on a single responsibility.',
            '- Version subflows carefully — changes affect all calling flows.',
            '',
            '### Performance Considerations',
            '- Avoid Look Up Records inside For Each loops (N+1 pattern). Instead, look up all needed records before the loop.',
            '- Use conditions on the trigger to minimize unnecessary flow executions.',
            '- Prefer built-in actions over Run Script for better platform optimization.',
            '- Long-running flows (with Wait actions) consume `wf_context` records — monitor and clean up stale contexts.',
            '- Scheduled flows that process large datasets should use pagination (limit + offset) or batch subflows.',
            '',
            '### Testing Best Practices',
            '- Test with records that match AND do not match trigger conditions.',
            '- Test each conditional branch (If / Else If / Else).',
            '- Test error paths by simulating action failures (invalid record, REST endpoint down).',
            '- Test subflow inputs at boundary values (null, empty string, max length).',
            '- Use Flow Designer\'s built-in test feature for individual action verification.',
            '- For scheduled flows, test with the expected data volume to identify performance issues.',
            '',
            '---',
            '',
            `Starting flow build for: **${desc}**`,
            `Trigger type: **${triggerType}**`,
            table !== '<not specified>'
              ? `Table: **${table}**`
              : 'Table: to be determined from requirement analysis',
              '',
              'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: [
            `Build a Flow Designer flow for the following requirement:`,
            `**Requirement:** ${desc}`,
            `**Trigger type:** ${triggerType}`,
            `**Table:** ${table}`,
            '',
            'Follow these steps exactly:',
            '',
            '### Step 1 — Understand the Requirement',
            'Parse the requirement and identify:',
            '- **Trigger event:** what causes this flow to start (record insert/update/delete, schedule, application event, inbound email).',
            `- **Trigger type:** ${triggerType}. Validate this is appropriate for the requirement; if not, recommend the correct trigger type and explain why.`,
            '- **Trigger conditions:** what conditions must be met on the trigger record (e.g., state changes from X to Y, priority = 1, category = "Hardware").',
            table !== '<not specified>'
              ? `- **Table:** ${table}. Use **get_table_schema** to verify the table exists and understand its fields, types, and relationships.`
              : '- **Table:** determine the correct table from the requirement. Use **get_table_schema** to verify it.',
            '- **Expected outcome:** what should happen when the flow completes successfully.',
            '- **Error scenarios:** what could go wrong and how should errors be handled.',
            '',
            '### Step 2 — Check Existing Flows for Conflicts',
            `Use **list_flows** to find all active flows${table !== '<not specified>' ? ` on the "${table}" table` : ''}. For each existing flow, note:`,
            '- Flow name, trigger type, trigger conditions.',
            '- Whether it overlaps with the new requirement (same trigger event + condition).',
            '- Whether it could conflict (competing updates to the same fields, contradictory actions).',
            '- Whether the new requirement could be met by modifying an existing flow instead of creating a new one.',
            '',
            'Also check **list_business_rules** on the same table — business rules on the same trigger event may conflict with or duplicate flow logic.',
            '',
            'If conflicts are found, recommend a resolution strategy before proceeding.',
            '',
            '### Step 3 — Design the Flow Structure',
            'Design the complete flow architecture before building:',
            '',
            '```',
            'FLOW: [Flow Name]',
            '  TRIGGER: [type] on [table] when [conditions]',
            '  ',
            '  TRY:',
            '    1. [Action Type] — [description]',
            '       Input: [data pills / values]',
            '       Output: [data pill name]',
            '    ',
            '    2. IF [condition]:',
            '         2a. [Action] — [description]',
            '       ELSE:',
            '         2b. [Action] — [description]',
            '    ',
            '    3. [Action] — [description]',
            '    ...',
            '  ',
            '  CATCH:',
            '    C1. Log Error — [error message with context]',
            '    C2. [Rollback Action] — [undo partial work]',
            '    C3. [Notification] — alert admin/support',
            '  ',
            '  OUTPUTS:',
            '    - [output_name]: [type] — [description]',
            '```',
            '',
            'For each action, specify:',
            '- The exact action type (Create Record, Update Record, Look Up Records, Run Script, etc.).',
            '- Input data pills and static values.',
            '- Output data pill names for downstream use.',
            '- Conditions for branching actions.',
            '',
            '### Step 4 — Identify Subflow Opportunities',
            'Determine if any logic should be extracted into subflows:',
            '- **Reusable patterns:** notification sequences, approval chains, record creation templates used in multiple flows.',
            '- **Complex sub-processes:** approval with escalation, multi-step provisioning, data validation suites.',
            '- **Testability:** isolated subflows are easier to test independently.',
            '',
            'For each subflow, define:',
            '- Name and description.',
            '- Typed inputs (name, type, mandatory flag).',
            '- Typed outputs (name, type).',
            '- Internal action sequence.',
            '',
            'Use **create_subflow** for each identified subflow before creating the main flow.',
            '',
            '### Step 5 — Generate Flow with Error Handling',
            'Build the flow using **create_flow** with:',
            '- Descriptive name following naming convention: `[Scope] - [Table] - [Purpose]` (e.g., "ITIL - Incident - Auto-Assign Critical").',
            '- Clear description explaining trigger, purpose, and expected outcomes.',
            '- Proper trigger configuration with conditions.',
            '- All actions in sequence with data pill bindings.',
            '- **Try/Catch wrapping** for all external calls, script actions, and record operations that could fail.',
            '- Rollback actions in the catch block to undo partial work.',
            '- Error logging with full context (flow name, trigger record sys_id, failed action, error message).',
            '- Error notification to administrators for critical failures.',
            '',
            'Validate:',
            '- No hardcoded sys_ids — use Look Up Record actions or flow inputs.',
            '- No N+1 patterns (Look Up Records inside For Each without prior aggregation).',
            '- All reference field data pills use dot-walking correctly.',
            '- Wait actions (if any) have appropriate timeout configuration.',
            '- Approval actions (if any) have correct rejection handling.',
            '',
            '### Step 6 — Create the Flow',
            'Use **create_flow** (and **create_subflow** for any subflows) to create the artifacts in ServiceNow. Report:',
            '- Flow sys_id and name.',
            '- Subflow sys_id(s) and name(s), if any.',
            '- Total action count and structure summary.',
            '',
            '### Step 7 — Suggest Test Scenarios',
            'Provide a comprehensive test matrix:',
            '',
            '| # | Scenario | Trigger Setup | Expected Flow Behavior | Expected Outcome |',
            '|---|----------|---------------|------------------------|------------------|',
            '',
            'Include at minimum:',
            '- **Happy path:** trigger fires, all conditions met, flow completes successfully end-to-end.',
            '- **Condition mismatch:** trigger fires but conditions are NOT met — flow should not execute.',
            '- **Branching:** test each conditional branch (If/Else) with appropriate trigger data.',
            '- **Error path:** simulate a failure in a critical action — verify catch block executes, rollback happens, notification is sent.',
            '- **Subflow isolation:** test each subflow independently with boundary inputs.',
            '- **Concurrency:** if applicable, test what happens when multiple flow instances run simultaneously on related records.',
            '- **Performance:** test with realistic data volume to verify the flow completes within acceptable time.',
            '- **Idempotency:** verify the flow produces correct results if triggered multiple times for the same record.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
