import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-rest-api',
  title: 'Build Scripted REST API',
  description:
    'Guided Scripted REST API endpoint design — authentication, input validation, versioning, error responses',
  category: 'build',
  arguments: [
    {
      name: 'description',
      description: 'what the API should do in plain language',
      required: true,
    },
    {
      name: 'api_name',
      description:
        'desired API name (e.g. "Asset Lookup"). If omitted, one will be derived from the description',
      required: false,
    },
    {
      name: 'http_methods',
      description:
        'comma-separated HTTP methods to implement: GET, POST, PUT, DELETE. Default: GET',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_core_records_query',
    'snow_intg_rest_messages_index',
    'snow_intg_rest_message_read',
    'snow_intg_rest_message_add',
    'snow_core_table_schema_read',
    'snow_scr_script_include_add',
  ],
  buildPrompt(args = {}) {
    const desc = args.description ?? '<not provided>';
    const apiName = args.api_name ?? '<derive from description>';
    const methods = args.http_methods ?? 'GET';

    return [
      {
        role: 'user',
        content: {
          type: 'text',
          text: [
            `Build a Scripted REST API.`,
            `**API Name:** ${apiName}`,
            `**HTTP Methods:** ${methods}`,
            `**Requirement:** ${desc}`,
            '',
            'Follow these steps exactly:',
            '',
            '### Step 1 — Understand the Requirement',
            'Restate the API requirement in your own words. Identify:',
            '- **Resources** — what entities does this API expose? (e.g., incidents, users, assets)',
            '- **Operations** — which HTTP methods map to which actions? (GET=read, POST=create, PUT=update, DELETE=remove)',
            '- **Consumers** — who will call this API? (external system, Service Portal, mobile app, MID Server)',
            '- **Authentication type** — Basic Auth, OAuth 2.0, API Key via header, or session-based',
            '- **Data volume** — expected request/response sizes, pagination needs',
            'Call out ambiguities and ask for clarification if needed.',
            '',
            '### Step 2 — Check Existing Scripted REST APIs',
            'Use **query_records** on `sys_ws_definition` (Scripted REST Services) to list all existing APIs.',
            'Check for:',
            '- **Namespace conflicts** — does an API with the same or similar name already exist?',
            '- **Endpoint collisions** — will the new resource paths conflict with existing ones?',
            '- **Reuse opportunities** — can an existing API be extended instead of creating a new one?',
            '',
            'Summarize existing APIs in a table:',
            '| Name | Namespace | Base Path | Active | Resources |',
            '|------|-----------|-----------|--------|-----------|',
            '',
            '### Step 3 — Design the API Structure',
            'Design the full API structure following ServiceNow Scripted REST API best practices:',
            '',
            '**API Registration (sys_ws_definition):**',
            '- **Name:** descriptive, PascalCase (e.g., `AssetLookupAPI`)',
            '- **API ID:** lowercase with underscores (e.g., `asset_lookup_api`)',
            '- **API Namespace:** use the scoped app namespace (e.g., `x_myapp`)',
            '- **Base API Path:** `/api/x_myapp/v1/<resource>` — always version the API',
            '',
            '**Resource Design (sys_ws_operation):**',
            'For each HTTP method, define:',
            '| Method | Resource Path | Purpose | Example |',
            '|--------|---------------|---------|---------|',
            '| GET | `/<resource>` | List records (with pagination) | `GET /api/x_app/v1/assets?limit=20&offset=0` |',
            '| GET | `/<resource>/{id}` | Get single record | `GET /api/x_app/v1/assets/abc123` |',
            '| POST | `/<resource>` | Create record | `POST /api/x_app/v1/assets` with JSON body |',
            '| PUT | `/<resource>/{id}` | Update record | `PUT /api/x_app/v1/assets/abc123` with JSON body |',
            '| DELETE | `/<resource>/{id}` | Delete record | `DELETE /api/x_app/v1/assets/abc123` |',
            '',
            '**Versioning Strategy:**',
            '- Use URL path versioning: `/api/x_app/v1/...`',
            '- Never break existing consumers — add v2 alongside v1 when needed',
            '- Deprecation headers: `X-API-Deprecated: true`, `X-API-Sunset: 2025-12-31`',
            '',
            '### Step 4 — Define Request/Response Schemas',
            'For each resource endpoint, define:',
            '',
            '**Request Schema:**',
            '- **Path parameters:** `{id}` — validate format (sys_id = 32-char hex)',
            '- **Query parameters:** `limit` (default 20, max 100), `offset`, `fields`, `sysparm_query`, `orderBy`',
            '- **Request body (POST/PUT):** JSON schema with required and optional fields',
            '- **Headers:** `Content-Type: application/json`, `Accept: application/json`, custom auth headers',
            '',
            '**Input Validation Rules:**',
            '- Validate sys_id format: `/^[a-f0-9]{32}$/`',
            '- Validate numeric parameters: `limit` must be 1-100, `offset` must be >= 0',
            '- Validate required body fields: return 400 with specific field errors',
            '- Sanitize string inputs: strip HTML, enforce max length, prevent GlideRecord injection',
            '- Validate enum values: only accept known values for choice fields',
            '',
            '**Response Schema:**',
            '```json',
            '{',
            '  "result": {',
            '    "status": "success",',
            '    "data": { ... },',
            '    "meta": {',
            '      "total": 150,',
            '      "limit": 20,',
            '      "offset": 0,',
            '      "next": "/api/x_app/v1/resource?limit=20&offset=20"',
            '    }',
            '  }',
            '}',
            '```',
            '',
            '**Error Response Schema:**',
            '```json',
            '{',
            '  "error": {',
            '    "message": "Record not found",',
            '    "detail": "No incident exists with sys_id abc123",',
            '    "status": "failure"',
            '  }',
            '}',
            '```',
            '',
            '### Step 5 — Generate Resource Scripts',
            'Write the scripted REST resource scripts for each HTTP method. Apply these patterns:',
            '',
            '**Request Object API (`request`):**',
            '- `request.pathParams` — map of URL path parameters (e.g., `{id}`)',
            '- `request.queryParams` — map of query string parameters',
            '- `request.body` — the parsed request body (RESTAPIRequestBody)',
            '- `request.getHeader(name)` — read request headers',
            '- `request.body.dataString` — raw body string',
            '- `request.body.data` — parsed object from JSON body',
            '- `request.body.nextEntry()` — iterate stream (for large payloads)',
            '- `request.uri` — full request URI',
            '',
            '**Response Object API (`response`):**',
            '- `response.setBody(obj)` — set JSON response body',
            '- `response.setStatus(code)` — set HTTP status code',
            '- `response.setHeader(name, value)` — set response headers',
            '- `response.setContentType(type)` — set Content-Type header',
            '',
            '**GlideRecord Operations:**',
            '- Use `GlideRecord` for CRUD, never raw SQL',
            '- Always use `setValue()` / `getValue()` for field access',
            '- Use `setLimit()` for list endpoints, enforce max of 100',
            '- Use `addEncodedQuery()` for complex filters, but NEVER concatenate user input — validate first',
            '- Use `chooseWindow(offset, offset + limit)` for pagination',
            '- Use `getRowCount()` sparingly — prefer `GlideAggregate` for total counts',
            '',
            '**Script Structure Template:**',
            '```javascript',
            '(function process(/*RESTAPIRequest*/ request, /*RESTAPIResponse*/ response) {',
            '    // 1. Parse and validate input',
            '    // 2. Check authorization',
            '    // 3. Perform GlideRecord operation',
            '    // 4. Build response',
            '    // 5. Handle errors with try/catch',
            '})(request, response);',
            '```',
            '',
            '**Error Handling with sn_ws_err:**',
            '- `new sn_ws_err.BadRequestError("message")` — 400',
            '- `new sn_ws_err.NotFoundError("message")` — 404',
            '- `new sn_ws_err.NotAcceptableError("message")` — 406',
            '- `new sn_ws_err.ConflictError("message")` — 409',
            '- `new sn_ws_err.UnsupportedMediaTypeError("message")` — 415',
            '- `new sn_ws_err.ServiceError("message")` — 500',
            '- For custom status codes: `response.setStatus(code); response.setBody({error: {...}});`',
            '',
            '### Step 6 — Implement Authentication & Authorization',
            'Implement layered security:',
            '',
            '**Authentication (who is calling):**',
            '- **Basic Auth:** ServiceNow handles natively; ensure HTTPS-only property is set',
            '- **OAuth 2.0:** configure OAuth Application, grant type, scopes. Use `oauth_entity` table',
            '- **API Key:** custom header validation (`X-API-Key`). Store key in `sys_properties` or credential store',
            '- **Mutual Auth (mTLS):** for high-security integrations, configure certificate validation',
            '',
            '**Authorization (what can they do):**',
            '- **ACL on the Scripted REST API:** set `Requires authentication` and `Requires role`',
            '- **In-script role checks:** `gs.hasRole("x_myapp.api_user")` for fine-grained control',
            '- **Row-level security:** filter GlideRecord results by caller\'s company/department/assignment_group',
            '- **Field-level security:** only return fields the caller is authorized to see',
            '- **Rate limiting:** check `request.getHeader("X-RateLimit-Remaining")` or implement custom throttling via properties',
            '',
            '**CORS Configuration:**',
            '- Set `glide.rest.cors.enabled` to true if browser clients will call the API',
            '- Configure allowed origins: `glide.rest.cors.rule.<name>.allowed_origins`',
            '- Set appropriate methods and headers in CORS rules',
            '',
            '### Step 7 — Add Error Handling',
            'Implement comprehensive error handling:',
            '',
            '**HTTP Status Code Map:**',
            '| Code | Meaning | When to Use |',
            '|------|---------|-------------|',
            '| 200 | OK | Successful GET, PUT |',
            '| 201 | Created | Successful POST |',
            '| 204 | No Content | Successful DELETE |',
            '| 400 | Bad Request | Invalid input, missing required fields |',
            '| 401 | Unauthorized | Missing or invalid authentication |',
            '| 403 | Forbidden | Authenticated but insufficient role/permissions |',
            '| 404 | Not Found | Record does not exist |',
            '| 405 | Method Not Allowed | HTTP method not supported on this resource |',
            '| 409 | Conflict | Duplicate record or concurrent modification |',
            '| 415 | Unsupported Media Type | Content-Type not application/json |',
            '| 422 | Unprocessable Entity | Valid JSON but fails business validation |',
            '| 429 | Too Many Requests | Rate limit exceeded |',
            '| 500 | Internal Server Error | Unexpected error (log details, return generic message) |',
            '',
            '**Error Response Best Practices:**',
            '- Always return a JSON error body, never raw text or HTML',
            '- Include a human-readable `message` and a machine-readable `error_code`',
            '- Never expose stack traces, sys_ids of internal records, or table names in error messages',
            '- Log full error details server-side with `gs.error()` for debugging',
            '- Wrap entire resource script in try/catch to prevent 500 errors from leaking implementation details',
            '',
            '### Step 8 — Create the Scripted REST API and Resources',
            'Use **create_rest_message** or guide the user to create the artifacts:',
            '',
            '1. **Create the Scripted REST Service** (`sys_ws_definition`):',
            '   - Name, API ID, namespace, base path',
            '   - Set `Requires authentication: true`',
            '   - Set required roles',
            '',
            '2. **Create each Resource** (`sys_ws_operation`):',
            '   - One resource per HTTP method + path combination',
            '   - Attach the generated script',
            '   - Set the HTTP method and relative path',
            '   - Configure query parameters and path parameters',
            '',
            '3. **Create supporting Script Includes** (if needed):',
            '   - Shared validation utilities',
            '   - Response builder helpers',
            '   - Business logic that might be reused across resources',
            '',
            'Report the sys_id and name of every created artifact.',
            '',
            '### Step 9 — Generate API Documentation and Test Scenarios',
            '',
            '**API Documentation:**',
            'Generate documentation in this format:',
            '```',
            'API: <name>',
            'Base URL: /api/<namespace>/v1/<resource>',
            'Authentication: <method>',
            'Content-Type: application/json',
            '',
            'Endpoints:',
            '  <METHOD> <path> — <description>',
            '    Request: <schema>',
            '    Response: <schema>',
            '    Errors: <possible error codes>',
            '```',
            '',
            '**Test Scenarios:**',
            'Provide a comprehensive test matrix:',
            '| # | Scenario | Method | Path | Body/Params | Expected Status | Expected Response |',
            '|---|----------|--------|------|-------------|-----------------|-------------------|',
            'Include at minimum:',
            '- Happy-path for each HTTP method',
            '- Missing required fields (400)',
            '- Invalid sys_id format (400)',
            '- Record not found (404)',
            '- Unauthorized request (401)',
            '- Forbidden — wrong role (403)',
            '- Duplicate creation attempt (409)',
            '- Pagination — first page, middle page, last page, beyond total',
            '- Large response — verify limit enforcement',
            '- Concurrent modification — optimistic locking if applicable',
            '- Special characters in input — verify sanitization',
            '- Empty body on POST/PUT (400)',
            '- Wrong Content-Type header (415)',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
