import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-app',
  title: 'Build Scoped App',
  description:
    'Build a complete scoped application from scratch — tables, scripts, ACLs, catalog item, tests, and update set packaging',
  category: 'build',
  arguments: [
    {
      name: 'name',
      description: 'application name',
      required: true,
    },
    {
      name: 'description',
      description: 'what the app does',
      required: true,
    },
    {
      name: 'scope',
      description: 'scope prefix e.g. x_myco',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_studio_scoped_app_add',
    'snow_scr_business_rule_add',
    'snow_scr_script_include_add',
    'snow_scr_client_script_add',
    'snow_scr_ui_policy_add',
    'snow_scr_ui_action_add',
    'snow_scr_acl_add',
    'snow_cat_catalog_item_add',
    'snow_us_update_set_add',
    'snow_atf_atf_suite_exec',
  ],
  buildPrompt(args = {}) {
    const name = args.name ?? '<not provided>';
    const description = args.description ?? '<not provided>';
    const scope = args.scope ?? 'x_custom';

    return [
      {
        role: 'user',
        content: {
          type: 'text',
          text: [
            `Build a complete scoped application: **${name}**`,
            `**Description:** ${description}`,
            `**Scope:** ${scope}`,
            '',
            'Execute all 7 phases below. After each phase, summarize what was created (name, sys_id, key configuration) before proceeding to the next.',
            '',
            '---',
            '',
            '## Phase 1 — App Setup',
            '',
            '1. **Create the scoped application** using **create_scoped_app** with:',
            `   - Name: "${name}"`,
            `   - Scope: "${scope}"`,
            `   - Description: "${description}"`,
            '2. **Create an update set** using **create_update_set** to track all artifacts.',
            '3. Set the update set as current so all subsequent artifacts are captured.',
            '4. Document the application metadata: sys_id, scope, version (start at 1.0.0).',
            '',
            '---',
            '',
            '## Phase 2 — Data Model',
            '',
            `Analyze the description ("${description}") and design the data model:`,
            '',
            '1. **Identify tables** needed. For each table:',
            '   - Define fields with types, max lengths, default values, and reference targets.',
            '   - Include standard fields: active (boolean), short_description (string), assigned_to (reference:sys_user), state (choice).',
            '   - Define choice lists for state/category fields.',
            '2. **Define relationships:**',
            '   - One-to-many: use reference fields.',
            '   - Many-to-many: use M2M tables (m2m_* naming convention).',
            '   - Parent-child: use the parent field pattern.',
            '3. **Create tables** with appropriate extends (if any — e.g., extend task for workflow-enabled tables).',
            '4. Output an entity-relationship summary showing all tables, fields, and relationships.',
            '',
            '---',
            '',
            '## Phase 3 — Server-Side Logic',
            '',
            'For each table, create the necessary server-side artifacts:',
            '',
            '### Business Rules',
            'Use **create_business_rule** for each:',
            '- **Before insert/update:** field validation, default value population, calculated fields.',
            '- **After insert/update:** cascading updates to related records, event generation, notification triggers.',
            '- **Async:** heavy operations (web service calls, batch processing).',
            '- Apply recursion guards on after rules, `setAbortAction` on validation rules.',
            '',
            '### Script Includes',
            'Use **create_script_include** for each:',
            '- **Utility class** for the app — encapsulate reusable business logic.',
            '- **Client-callable Script Include** (extends AbstractAjaxProcessor) for any server data the UI needs.',
            '- Follow the Class.create() / prototype pattern.',
            '- Include JSDoc for all public methods.',
            '',
            '### Scheduled Jobs (if applicable)',
            '- Identify any periodic tasks: cleanup, sync, report generation.',
            '- Document the schedule (daily, weekly, on-demand) and the script logic.',
            '',
            '---',
            '',
            '## Phase 4 — Client-Side UX',
            '',
            '### Client Scripts',
            'Use **create_client_script** for each:',
            '- **onChange:** dynamic field behavior (show/hide, set mandatory, populate references).',
            '- **onLoad:** form initialization, user-specific defaults.',
            '- **onSubmit:** client-side validation (always backed by server-side validation).',
            '- Use GlideAjax to call the Script Includes from Phase 3 — never use synchronous GlideRecord.',
            '',
            '### UI Policies',
            'Use **create_ui_policy** for each:',
            '- Simple show/hide/mandatory/read-only rules that do NOT require scripting.',
            '- Prefer UI Policies over client scripts for declarative field behavior.',
            '',
            '### UI Actions',
            'Use **create_ui_action** for each:',
            '- Custom form buttons (e.g., "Approve", "Escalate", "Generate Report").',
            '- List context-menu actions for bulk operations.',
            '- Include both client-side and server-side script sections where appropriate.',
            '',
            '---',
            '',
            '## Phase 5 — Security',
            '',
            'Design a comprehensive security model:',
            '',
            '### Roles',
            `Define application roles (e.g., ${scope}.user, ${scope}.admin, ${scope}.manager):`,
            '- Document what each role grants access to.',
            '- Map roles to user personas.',
            '',
            '### ACLs (Access Control Lists)',
            'Use **create_acl** for each. Create three layers:',
            '',
            '1. **Table-level ACLs:**',
            '   - Create: who can create records.',
            '   - Read: who can view the table/list.',
            '   - Write: who can edit records.',
            '   - Delete: who can delete records.',
            '',
            '2. **Field-level ACLs:**',
            '   - Protect sensitive fields (e.g., approval status, financial data).',
            '   - Make certain fields read-only for non-admin roles.',
            '',
            '3. **Row-level ACLs (conditions/scripts):**',
            '   - Users can only see records assigned to them or their group.',
            '   - Managers can see all records in their department.',
            '   - Admins can see everything.',
            '',
            'Test each ACL mentally: "Can user X with role Y perform operation Z on this record?" — document the expected results.',
            '',
            '---',
            '',
            '## Phase 6 — Service Catalog',
            '',
            'Create a catalog item so end-users can request/interact with the application:',
            '',
            '1. **Catalog Item** using **create_catalog_item**:',
            `   - Name: "Request ${name}"`,
            '   - Category: choose the appropriate category.',
            '   - Description: user-facing explanation of what they are requesting.',
            '',
            '2. **Variables:**',
            '   - Define catalog variables (text, reference, select box, checkbox, etc.).',
            '   - Set mandatory flags and validation (regex, reference qualifiers).',
            '   - Organize with variable sets if there are reusable field groups.',
            '',
            '3. **Approval Rules:**',
            '   - Define who approves requests (manager, specific group, auto-approve for certain roles).',
            '   - Multi-level approval if needed.',
            '',
            '4. **Fulfillment:**',
            '   - Define what happens after approval: record creation, task generation, notification.',
            '   - Use a catalog task or flow for fulfillment logic.',
            '',
            '---',
            '',
            '## Phase 7 — Quality & Packaging',
            '',
            '### Code Review',
            'Review ALL artifacts created in Phases 2–6:',
            '- No hardcoded sys_ids (use `gs.getProperty()` or reference qualifiers).',
            '- No N+1 query patterns in business rules or script includes.',
            '- No `eval()` or dynamic script execution.',
            '- Consistent naming convention: `${scope}_table_name`, `${scope}.RoleName`.',
            '- All scripts have JSDoc comment blocks.',
            '- Client scripts do not expose sensitive logic (security checks are server-side).',
            '',
            '### Test Plan',
            'Generate a comprehensive ATF test suite covering:',
            '- Business rule behavior (before/after/async for each table).',
            '- Script include methods (unit tests for each public method).',
            '- Client script behavior (form interactions via ATF client-side steps).',
            '- ACL enforcement (role-based access tests).',
            '- Catalog item flow (request → approval → fulfillment).',
            '- End-to-end integration test (full lifecycle of a record).',
            '',
            'Use **run_atf_suite** to execute the suite and report results.',
            '',
            '### Update Set Packaging',
            'Ensure the update set contains ALL artifacts. Provide:',
            '- Complete artifact inventory (table: name → sys_id).',
            '- Installation instructions.',
            '- Configuration guide (properties to set, roles to assign).',
            '- Known limitations or prerequisites.',
            '',
            '---',
            '',
            '## Final Deliverable',
            '',
            'After completing all 7 phases, provide a summary report:',
            '',
            '| Category | Count | Details |',
            '|----------|-------|---------|',
            '| Tables | N | list |',
            '| Business Rules | N | list |',
            '| Script Includes | N | list |',
            '| Client Scripts | N | list |',
            '| UI Policies | N | list |',
            '| UI Actions | N | list |',
            '| ACLs | N | list |',
            '| Roles | N | list |',
            '| Catalog Items | N | list |',
            '| ATF Tests | N | pass/fail |',
            '| Update Set | sys_id | name |',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
