import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'build-test-plan',
  title: 'Build Test Plan',
  description:
    'Generate comprehensive ATF test suites from requirements or existing artifacts — covers all testable ServiceNow components',
  category: 'build',
  arguments: [
    {
      name: 'target',
      description:
        'business rule name/sys_id, script include, client script, flow, or describe the feature to test',
      required: true,
    },
    {
      name: 'type',
      description: 'unit, integration, regression, smoke. Default: integration',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_atf_atf_suite_exec',
    'snow_atf_atf_test_exec',
    'snow_atf_atf_suites_index',
    'snow_atf_atf_tests_index',
    'snow_scr_business_rule_read',
    'snow_scr_script_include_read',
    'snow_scr_client_script_read',
    'snow_core_records_query',
    'snow_core_table_schema_read',
  ],
  buildPrompt(args = {}) {
    const target = args.target ?? '<not provided>';
    const type = args.type ?? 'integration';

    return [
      {
        role: 'user',
        content: {
          type: 'text',
          text: [
            `Generate a comprehensive **${type}** test plan for: **${target}**`,
            '',
            'Follow these steps:',
            '',
            '### Step 1 — Identify the Artifact(s) Under Test',
            `Determine what "${target}" refers to. Use the appropriate tool to retrieve details:`,
            '- **get_business_rule** if it is a business rule name or sys_id.',
            '- **get_script_include** if it is a script include.',
            '- **get_client_script** if it is a client script.',
            '- **query_records** on sys_hub_flow for flows, sys_ui_policy for UI policies, sys_security_acl for ACLs, sc_cat_item for catalog items.',
            '- If the target is a plain-language feature description, identify ALL artifacts that implement the feature.',
            '',
            'Retrieve the full source code and configuration of each artifact. Use **get_table_schema** for tables involved.',
            '',
            '### Step 2 — Analyze Test Coverage Requirements',
            `Based on the artifact type(s), apply the relevant test strategy below. Test type: **${type}**.`,
            '',
            '---',
            '',
            '#### Business Rules',
            '- **Before rules (validation):** test that `setAbortAction` fires for invalid data and does NOT fire for valid data.',
            '- **Before rules (data manipulation):** verify field values are correctly set/transformed before insert/update.',
            '- **After rules:** verify downstream effects (related record updates, events generated, notifications sent).',
            '- **Async rules:** verify the event is registered and the async processing completes correctly.',
            '- **Condition evaluation:** test with records that match AND do not match the condition.',
            '- **Update vs Insert:** test both operations if the rule fires on both.',
            '',
            '#### Script Includes',
            '- Test each **public method** individually.',
            '- Test with valid inputs, invalid inputs, null/undefined inputs, and boundary values.',
            '- Test error handling paths — verify exceptions are thrown or handled gracefully.',
            '- If the Script Include extends AbstractAjaxProcessor, test via GlideAjax simulation.',
            '- Test any caching behavior or state management.',
            '',
            '#### Client Scripts',
            '- **onChange:** test with various newValue/oldValue combinations including empty string and null.',
            '- **onLoad:** verify form state after load (field visibility, mandatory states, default values).',
            '- **onSubmit:** test that valid submissions proceed and invalid submissions are blocked.',
            '- Use ATF **client-side test steps** (UI interaction steps) to simulate user behavior.',
            '- Test with different user roles (admin vs non-admin) if behavior is role-dependent.',
            '',
            '#### UI Policies',
            '- Verify field **visibility** states (visible/hidden) based on condition.',
            '- Verify field **mandatory** states based on condition.',
            '- Verify field **read-only** states based on condition.',
            '- Test condition boundaries — one record that matches, one that does not.',
            '- Test reverse behavior when condition becomes false (if "reverse if false" is enabled).',
            '',
            '#### Flows / Flow Designer',
            '- Test **trigger conditions** — verify the flow fires for matching records and does NOT fire for non-matching.',
            '- Test each **flow step/action** in isolation where possible.',
            '- Test the **end-to-end flow** with realistic data.',
            '- Test **error handling** — what happens when a step fails (fault handler, error output).',
            '- Test **subflow** invocations with various inputs.',
            '- Test **approval steps** with approve and reject paths.',
            '',
            '#### ACLs (Access Control Lists)',
            '- Build a role matrix and test every combination:',
            '  - Admin user (should bypass ACLs).',
            '  - User with the required role(s).',
            '  - User WITHOUT the required role(s).',
            '  - User with partial roles (if multiple roles are required).',
            '- Test all operations the ACL governs: read, write, create, delete.',
            '- Test row-level conditions if the ACL has a script or condition.',
            '',
            '#### Catalog Items',
            '- Test **variable validation** — mandatory variables, regex validators, reference qualifiers.',
            '- Test **catalog client scripts** and **variable sets**.',
            '- Test **approval flow** — verify approval is requested from the correct group/user.',
            '- Test **fulfillment** — verify the requested item is provisioned correctly.',
            '- Test **order guides** if the item is part of one.',
            '',
            '#### REST API (Scripted REST)',
            '- Test each endpoint with valid payloads — verify response status and body.',
            '- Test with invalid/malformed payloads — verify appropriate error responses.',
            '- Test authentication — unauthenticated, basic auth, OAuth, API key.',
            '- Test authorization — verify role enforcement.',
            '- Test rate limiting and pagination if applicable.',
            '',
            '---',
            '',
            '### Step 3 — Generate the Test Suite Specification',
            'For EACH test case, provide:',
            '',
            '| Field | Description |',
            '|-------|-------------|',
            '| **Test ID** | Unique identifier (e.g., TC-BR-001) |',
            '| **Test Name** | Descriptive name |',
            '| **Artifact** | The specific artifact under test |',
            '| **Category** | unit / integration / regression / smoke |',
            '| **Priority** | P1 (critical) / P2 (important) / P3 (nice-to-have) |',
            '| **Setup Steps** | Create test data, impersonate users, set system properties |',
            '| **Test Steps** | Step-by-step actions to trigger and verify behavior |',
            '| **Expected Result** | Precise, verifiable assertion(s) |',
            '| **Teardown Steps** | Delete test records, restore impersonation, reset properties |',
            '| **Edge Cases** | Boundary conditions, null values, concurrent modifications |',
            '',
            '### Step 4 — Check for Existing Tests',
            'Use **list_atf_suites** and **list_atf_tests** to find any existing tests for these artifacts. Report overlap and recommend whether to extend existing tests or create new ones.',
            '',
            '### Step 5 — Create and Run the ATF Suite',
            'If the user wants to proceed with creation:',
            '1. Use the ServiceNow ATF tools to create the test suite and individual test cases.',
            '2. Use **run_atf_suite** to execute the suite.',
            '3. Report results — pass/fail per test, execution time, any failures with details.',
            '',
            '### Step 6 — Output Summary',
            'Provide a final summary table:',
            '',
            '| Metric | Value |',
            '|--------|-------|',
            '| Total test cases | N |',
            '| P1 (critical) | N |',
            '| P2 (important) | N |',
            '| P3 (nice-to-have) | N |',
            '| Artifact types covered | list |',
            '| Estimated execution time | N min |',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
    ];
  },
};

export default capability;
