import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'docs-app',
  title: 'Document Application',
  description:
    'Auto-generate comprehensive documentation for a scoped application — tables, scripts, flows, ACLs, catalog items, and architecture',
  category: 'docs',

  arguments: [
    {
      name: 'app',
      description: 'scoped app name or scope prefix e.g. x_myco_app',
      required: true,
    },
  ],

  recommendedTools: [
    'snow_studio_scoped_app_read',
    'snow_core_records_query',
    'snow_core_table_schema_read',
    'snow_scr_business_rules_index',
    'snow_scr_script_includes_index',
    'snow_scr_client_scripts_index',
    'snow_scr_ui_policies_index',
    'snow_scr_ui_actions_index',
    'snow_scr_acls_index',
    'snow_flow_flows_index',
    'snow_cat_catalog_items_index',
  ],

  buildPrompt(args) {
    const app = args?.app ?? 'Document the application';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Document Application',
            '',
            'I am a **ServiceNow application documentation specialist**. I generate comprehensive',
            'documentation for a scoped application by discovering and documenting every artifact type.',
            '',
            '## Documentation Sections',
            '',
            '### 1. Application Overview',
            '',
            'Use `get_scoped_app` and `query_records` on `sys_scope` to gather:',
            '- Application name, scope (e.g. `x_myco_app`)',
            '- Version, vendor, description',
            '- License model and entitlements',
            '- Dependencies on other apps/plugins',
            '- Application menus and modules',
            '',
            '### 2. Data Model',
            '',
            'Use `get_table_schema` and `query_records` on `sys_db_object`, `sys_dictionary`, `sys_relationship`:',
            '',
            'For each table in the app scope:',
            '- **Table definition** — name, label, extends, access controls',
            '- **Fields** — name, type, max length, mandatory, default value, reference target',
            '- **Relationships** — parent-child, reference, many-to-many',
            '- **Indexes** — indexed fields and composite indexes',
            '- **Number prefix** — auto-number configuration',
            '- **Table hierarchy** — inheritance chain and extended tables',
            '',
            'Output: ER diagram description and field-level detail tables',
            '',
            '### 3. Server-Side Logic',
            '',
            '#### Business Rules',
            'Use `list_business_rules` filtered by app scope:',
            '- Table, when (before/after/async/display), order',
            '- Filter conditions and role conditions',
            '- Insert/update/delete/query operations',
            '- Script summary — what it does in plain language',
            '- Active/inactive status',
            '',
            '#### Script Includes',
            'Use `list_script_includes` filtered by app scope:',
            '- Name, API name (scope.ClassName)',
            '- Client callable (true/false)',
            '- Methods and their purposes',
            '- Dependencies on other script includes',
            '- Extends/implements relationships',
            '',
            '#### Fix Scripts',
            'Use `query_records` on `sys_script_fix`:',
            '- Name, description, run count',
            '- What data it modifies',
            '- When it should be run (install, upgrade, manual)',
            '',
            '#### Scheduled Jobs',
            'Use `query_records` on `sysauto_script`:',
            '- Name, schedule/frequency, run-as user',
            '- What it does, tables affected',
            '- Active/inactive, last run status',
            '',
            '### 4. Client-Side Logic',
            '',
            '#### Client Scripts',
            'Use `list_client_scripts` filtered by app scope:',
            '- Type (onChange, onLoad, onSubmit, onCellEdit)',
            '- Table and field (for onChange)',
            '- What it does — UI behavior, validations, field manipulation',
            '- Global vs. scoped',
            '',
            '#### UI Policies',
            'Use `list_ui_policies` filtered by app scope:',
            '- Table, order, conditions',
            '- Actions: mandatory, visible, read-only (for which fields)',
            '- Script actions (if any)',
            '- Reverse if false behavior',
            '',
            '#### UI Actions',
            'Use `list_ui_actions` filtered by app scope:',
            '- Table, name, label, action type (form button, list button, link)',
            '- Client/server script behavior',
            '- Conditions and role requirements',
            '',
            '### 5. Security Model',
            '',
            '#### Roles',
            'Use `query_records` on `sys_user_role`:',
            '- Role names and descriptions',
            '- Role hierarchy (contains/contained by)',
            '- Application-specific roles vs. inherited platform roles',
            '',
            '#### ACLs',
            'Use `list_acls` filtered by app scope:',
            '- **Table-level ACLs** — read, write, create, delete per role',
            '- **Field-level ACLs** — restricted fields and who can access them',
            '- **Row-level ACLs** — conditional access based on record values',
            '- Advanced scripts in ACLs',
            '- ACL evaluation order',
            '',
            '#### Data Policies',
            'Use `query_records` on `sys_data_policy2`:',
            '- Read-only fields, mandatory fields (enforced at database level)',
            '- Conditions under which policies apply',
            '',
            '### 6. Flows & Automation',
            '',
            'Use `list_flows` and `query_records` on flow-related tables:',
            '- **Flows** — trigger type, trigger conditions, actions, subflow calls',
            '- **Subflows** — inputs/outputs, reusable logic',
            '- **Actions** — custom flow actions in the app scope',
            '- **Workflows (legacy)** — if any classic workflows exist',
            '',
            '### 7. Service Catalog',
            '',
            'Use `list_catalog_items` and `query_records`:',
            '- **Catalog items** — name, category, description, price',
            '- **Variables** — variable sets, types, mandatory, reference qualifiers',
            '- **Variable sets** — reusable variable groups',
            '- **Approval rules** — who approves, conditions, stages',
            '- **Fulfillment** — workflow/flow that processes the request',
            '- **Order guides** — multi-item ordering configurations',
            '',
            '### 8. Integrations',
            '',
            '#### REST Messages',
            'Use `query_records` on `sys_rest_message`, `sys_rest_message_fn`:',
            '- Outbound REST endpoints, methods, authentication',
            '- Request/response format, headers',
            '',
            '#### Scripted REST APIs',
            'Use `query_records` on `sys_ws_definition`, `sys_ws_operation`:',
            '- Inbound API resources, methods, ACLs',
            '- Request/response format',
            '',
            '#### Transform Maps',
            'Use `query_records` on `sys_transform_map`, `sys_transform_entry`:',
            '- Source-to-target field mappings',
            '- Transform scripts and conditions',
            '',
            '#### Import Sets',
            'Use `query_records` on `sys_data_source`:',
            '- Data sources, type (file, JDBC, REST, etc.)',
            '- Scheduled imports and frequency',
            '',
            '### 9. Portal',
            '',
            'Use `query_records` on portal-related tables:',
            '- **Widgets** — name, template (HTML), client script, server script, CSS',
            '- **Pages** — URL, layout, widget instances',
            '- **Angular providers** — services, factories',
            '- **Portal themes** — branding, CSS variables',
            '',
            '### 10. Notifications',
            '',
            'Use `query_records` on `sysevent_email_action`, `sysevent_email_template`:',
            '- **Email notifications** — event/condition, recipients, template',
            '- **Email templates** — subject, body (with variable replacements)',
            '- **SMS/push notifications** — if configured',
            '',
            '## Output Format',
            '',
            'Generate the complete documentation in clean markdown format:',
            '',
            '```',
            '# [Application Name] — Technical Documentation',
            '## Version: [version]  |  Scope: [scope]',
            '',
            '### Table of Contents',
            '1. Application Overview',
            '2. Data Model',
            '3. Server-Side Logic',
            '4. Client-Side Logic',
            '5. Security Model',
            '6. Flows & Automation',
            '7. Service Catalog',
            '8. Integrations',
            '9. Portal',
            '10. Notifications',
            '',
            '[Each section with tables, descriptions, and cross-references]',
            '```',
            '',
            'The documentation should be ready for direct use in a wiki, Confluence, or markdown repository.',
            '',
            '---',
            '',
            'Starting application documentation.',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: app,
        },
      },
    ];
  },
};

export default capability;
