import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'docs-release',
  title: 'Generate Release Notes',
  description:
    'Generate release notes from update set contents — summarize all changes, categorize by type, highlight breaking changes',
  category: 'docs',

  arguments: [
    {
      name: 'updateset',
      description: 'update set name or sys_id',
      required: true,
    },
    {
      name: 'version',
      description: 'version number for the release e.g. 2.1.0',
      required: false,
    },
  ],

  recommendedTools: [
    'snow_us_update_sets_index',
    'snow_core_records_query',
    'snow_scr_business_rule_read',
    'snow_scr_script_include_read',
    'snow_scr_client_script_read',
  ],

  buildPrompt(args) {
    const updateset = args?.updateset ?? 'Generate release notes';
    const version = args?.version ?? 'UNRELEASED';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Generate Release Notes',
            '',
            `**Version:** ${version}`,
            '',
            'I am a **release notes specialist**. I analyze update set contents and generate',
            'structured, categorized release notes with breaking change highlights.',
            '',
            '## Release Notes Workflow',
            '',
            '### Step 1 — Fetch Update Set Contents',
            '',
            'Use `list_update_sets` to find the update set, then `query_records` on',
            '`sys_update_xml` filtered by `update_set` to retrieve every customer update:',
            '- Record type (table name)',
            '- Action (insert, update, delete)',
            '- Target record name and sys_id',
            '- Payload summary (what fields changed)',
            '- Update set name and parent set (if batched)',
            '',
            '### Step 2 — Categorize Changes',
            '',
            'Sort each change into one of these categories:',
            '',
            '| Category | Icon | Criteria |',
            '|----------|------|----------|',
            '| **New Features** | NEW | New records (inserts) that add functionality |',
            '| **Enhancements** | ENHANCED | Updates to existing records that improve functionality |',
            '| **Bug Fixes** | FIXED | Changes that correct defective behavior |',
            '| **Security** | SECURITY | ACL changes, role modifications, security policies |',
            '| **Configuration** | CONFIG | Property changes, system settings, UI adjustments |',
            '| **Deprecated** | DEPRECATED | Features marked for removal in future releases |',
            '',
            'Categorization heuristics:',
            '- Inserts on functional tables (sys_script, sys_script_include, etc.) = New Features',
            '- Updates with "fix" in description or work notes = Bug Fixes',
            '- ACL/role table changes = Security',
            '- sys_properties changes = Configuration',
            '- Use context clues from record names and descriptions',
            '',
            '### Step 3 — Detail Each Change',
            '',
            'For each change, document:',
            '',
            '| Field | Description |',
            '|-------|-------------|',
            '| **Type** | Artifact type: BR, SI, CS, ACL, Flow, Catalog Item, Table, etc. |',
            '| **Table Affected** | Which table this artifact operates on |',
            '| **Name** | Human-readable name of the artifact |',
            '| **What Changed** | Summary of the modification in plain language |',
            '| **Impact** | Who/what is affected by this change |',
            '',
            'Use `get_business_rule`, `get_script_include`, `get_client_script` to fetch',
            'details when the update XML payload is insufficient.',
            '',
            '### Step 4 — Highlight Breaking Changes',
            '',
            'Flag changes that may break existing functionality:',
            '',
            '**Schema Changes (BREAKING)**',
            '- New mandatory fields on existing tables',
            '- Field type changes (e.g., string to reference)',
            '- Deleted fields or tables',
            '- Changed field max length (shorter)',
            '',
            '**ACL Changes (BREAKING)**',
            '- More restrictive ACLs (users lose access)',
            '- Removed ACLs (security gap)',
            '- Changed ACL conditions',
            '',
            '**Script Interface Changes (BREAKING)**',
            '- Script Include method signature changes',
            '- Removed or renamed public methods',
            '- Changed return types or behavior',
            '- Modified API endpoints (Scripted REST)',
            '',
            '**Behavioral Changes (POTENTIALLY BREAKING)**',
            '- Business rule condition changes',
            '- Flow trigger modifications',
            '- Notification recipient changes',
            '- Catalog variable changes affecting fulfillment',
            '',
            '### Step 5 — Generate Formatted Release Notes',
            '',
            '## Output Format',
            '',
            '```',
            `# Release Notes — v${version}`,
            'Release Date: [date]',
            'Update Set: [name]',
            '',
            '---',
            '',
            '## Breaking Changes',
            '',
            '> These changes require attention during upgrade. Review before deploying.',
            '',
            '- **[BREAKING]** [type] — [description of what changed and migration steps]',
            '',
            '---',
            '',
            '## New Features',
            '',
            '- **[type]** [name] — [description]',
            '  - Table: [affected table]',
            '  - Details: [additional context]',
            '',
            '## Enhancements',
            '',
            '- **[type]** [name] — [description]',
            '',
            '## Bug Fixes',
            '',
            '- **[type]** [name] — [what was broken and how it was fixed]',
            '',
            '## Security',
            '',
            '- **[type]** [name] — [security change description]',
            '',
            '## Configuration Changes',
            '',
            '- **[type]** [name] — [what was configured]',
            '',
            '---',
            '',
            '## Change Summary',
            '',
            '| Category | Count |',
            '|----------|-------|',
            '| New Features | X |',
            '| Enhancements | X |',
            '| Bug Fixes | X |',
            '| Security | X |',
            '| Configuration | X |',
            '| **Total** | **X** |',
            '',
            '## Artifact Breakdown',
            '',
            '| Artifact Type | Inserts | Updates | Deletes |',
            '|---------------|---------|---------|---------|',
            '| Business Rules | X | X | X |',
            '| Script Includes | X | X | X |',
            '| Client Scripts | X | X | X |',
            '| ACLs | X | X | X |',
            '| ... | ... | ... | ... |',
            '```',
            '',
            '---',
            '',
            `Starting release notes generation for version: **${version}**.`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: updateset,
        },
      },
    ];
  },
};

export default capability;
