import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'docs-runbook',
  title: 'Generate Runbook',
  description:
    'Generate operational runbook for a service, application, or CI — incident response steps, health checks, escalation paths',
  category: 'docs',

  arguments: [
    {
      name: 'service',
      description: 'service name, CI name, or application name',
      required: true,
    },
  ],

  recommendedTools: [
    'snow_core_cmdb_ci_query',
    'snow_core_cmdb_ci_read',
    'snow_core_relationships_index',
    'snow_core_records_query',
    'snow_kb_knowledge_query',
    'snow_scr_business_rules_index',
    'snow_rpt_scheduled_jobs_index',
    'snow_flow_flows_index',
  ],

  buildPrompt(args) {
    const service = args?.service ?? 'Generate the runbook';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Generate Runbook',
            '',
            'I am an **operational runbook specialist**. I generate comprehensive runbooks for',
            'services, applications, and configuration items by gathering information from the',
            'CMDB, knowledge base, automation, and operational data.',
            '',
            '## Runbook Sections',
            '',
            '### 1. Service Overview & Architecture',
            '',
            'Use `search_cmdb_ci`, `get_cmdb_ci`, and `query_records` to document:',
            '- Service/CI name, class, operational status',
            '- Business criticality and tier (Tier 1/2/3)',
            '- Owner, support group, managed by',
            '- Environment (production, staging, dev)',
            '- Architecture description — what the service does, how it works',
            '- Technology stack and platform dependencies',
            '- SLA commitments (uptime, response time)',
            '',
            '### 2. Key CIs & Dependencies',
            '',
            'Use `get_cmdb_ci` and `list_relationships` to map:',
            '',
            '**Upstream Dependencies (this service depends on):**',
            '- CI name, class, operational status',
            '- Impact if upstream fails (full outage, degraded, none)',
            '- Failover/redundancy available',
            '',
            '**Downstream Dependants (depend on this service):**',
            '- CI name, class, business criticality',
            '- Impact if this service fails',
            '- Number of end users affected',
            '',
            '**Infrastructure Components:**',
            '- Servers, load balancers, databases',
            '- Network segments, firewalls, DNS',
            '- Storage, backup systems',
            '',
            'Output: Dependency diagram description (upstream -> service -> downstream)',
            '',
            '### 3. Health Check Procedures',
            '',
            'Use `query_records`, `list_scheduled_jobs`, and `search_knowledge` to define:',
            '',
            '| Check | Command/Procedure | Expected Result | Frequency |',
            '|-------|-------------------|-----------------|-----------|',
            '| Service availability | [how to check] | [expected response] | Every 5 min |',
            '| Database connectivity | [how to check] | [expected state] | Every 5 min |',
            '| Queue depth | [how to check] | [threshold] | Every 15 min |',
            '| Scheduled jobs | [how to check] | [all green] | Daily |',
            '| Log error rate | [how to check] | [< threshold] | Every 15 min |',
            '| Integration endpoints | [how to check] | [200 OK] | Every 5 min |',
            '| Certificate expiry | [how to check] | [> 30 days] | Weekly |',
            '',
            '### 4. Common Incidents & Troubleshooting',
            '',
            'Use `query_records` on `incident` (filtered by CI) and `search_knowledge` to compile:',
            '',
            'For each common incident pattern:',
            '',
            '```',
            'INCIDENT: [Short description pattern]',
            'Frequency: [how often this occurs]',
            'Severity: [typical priority]',
            'Symptoms:',
            '  - [symptom 1]',
            '  - [symptom 2]',
            'Root Cause: [known cause]',
            'Resolution Steps:',
            '  1. [step with detail]',
            '  2. [step with detail]',
            '  ...',
            'Verification: [how to confirm resolution]',
            'Prevention: [how to avoid recurrence]',
            'KB Article: [link if available]',
            '```',
            '',
            '### 5. Escalation Matrix',
            '',
            'Use `query_records` on `sys_user_group`, `cmdb_ci_service`, and related tables:',
            '',
            '| Level | When to Escalate | Contact | Response Time |',
            '|-------|------------------|---------|---------------|',
            '| L1 | Initial triage, known issues | [support group] | 15 min |',
            '| L2 | Unknown issues, requires investigation | [engineering team] | 30 min |',
            '| L3 | Complex issues, code changes needed | [dev team / vendor] | 1 hour |',
            '| Management | P1 incidents, SLA breach risk | [service owner / manager] | Immediate |',
            '| Executive | Major outage, customer impact | [director / VP] | Immediate |',
            '',
            'Include: on-call rotation information, bridge/war room procedures, vendor contacts',
            '',
            '### 6. Maintenance Windows & Procedures',
            '',
            'Use `query_records` and `list_scheduled_jobs` to document:',
            '',
            '**Regular Maintenance:**',
            '- Scheduled window (day/time/timezone)',
            '- What maintenance activities are performed',
            '- Pre-maintenance checklist',
            '- Post-maintenance validation steps',
            '- User notification requirements',
            '',
            '**Patching Procedures:**',
            '- Patch schedule and approval process',
            '- Pre-patch backup requirements',
            '- Patch application steps',
            '- Post-patch validation',
            '',
            '### 7. Recovery Procedures',
            '',
            'Use `search_knowledge` and `query_records` to compile:',
            '',
            '**Service Restart:**',
            '1. Pre-restart checks (save state, drain connections)',
            '2. Restart command/procedure',
            '3. Post-restart validation',
            '4. Expected recovery time',
            '',
            '**Failover:**',
            '1. Failover trigger conditions',
            '2. Automatic vs. manual failover',
            '3. Failover execution steps',
            '4. DNS/load balancer updates',
            '5. Verification of failover success',
            '6. Failback procedure',
            '',
            '**Rollback:**',
            '1. Rollback trigger conditions',
            '2. Data backup verification',
            '3. Rollback execution steps',
            '4. Post-rollback validation',
            '5. Communication to stakeholders',
            '',
            '**Disaster Recovery:**',
            '- RPO (Recovery Point Objective)',
            '- RTO (Recovery Time Objective)',
            '- DR site details and activation procedure',
            '- Data restoration steps',
            '',
            '### 8. Monitoring & Alerting',
            '',
            'Use `query_records` and `list_flows` to document:',
            '',
            '| Metric | Threshold (Warning) | Threshold (Critical) | Alert Channel |',
            '|--------|---------------------|----------------------|---------------|',
            '| Response time | > 2s | > 5s | [email/SMS/PagerDuty] |',
            '| Error rate | > 1% | > 5% | [channel] |',
            '| CPU utilization | > 80% | > 95% | [channel] |',
            '| Memory usage | > 80% | > 95% | [channel] |',
            '| Queue depth | > 1000 | > 5000 | [channel] |',
            '| Disk usage | > 80% | > 90% | [channel] |',
            '',
            '- Dashboard URLs and access instructions',
            '- Log locations and search queries for common issues',
            '- Alert acknowledgment and escalation procedures',
            '',
            '## Output Format',
            '',
            '```',
            '# Operational Runbook: [Service Name]',
            '## Version: [date]  |  Owner: [team]  |  Criticality: [tier]',
            '',
            '### Table of Contents',
            '1. Service Overview & Architecture',
            '2. Key CIs & Dependencies',
            '3. Health Check Procedures',
            '4. Common Incidents & Troubleshooting',
            '5. Escalation Matrix',
            '6. Maintenance Windows & Procedures',
            '7. Recovery Procedures',
            '8. Monitoring & Alerting',
            '',
            '[Each section fully populated with operational detail]',
            '```',
            '',
            '---',
            '',
            'Starting runbook generation.',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: service,
        },
      },
    ];
  },
};

export default capability;
