import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'ops-triage',
  title: 'Incident Triage',
  description:
    'P1/P2 incident triage — fetch details, assess impact via CMDB, check SLAs, search KB, suggest resolution, draft communications',
  category: 'ops',

  arguments: [
    {
      name: 'incident',
      description:
        'incident number e.g. INC0012345 or describe the situation',
      required: true,
    },
    {
      name: 'action',
      description:
        'triage, escalate, communicate, review. Default: triage',
      required: false,
    },
  ],

  recommendedTools: [
    'snow_inc_incident_read',
    'snow_inc_incident_modify',
    'snow_inc_work_note_annotate',
    'snow_inc_comment_annotate',
    'snow_core_records_query',
    'snow_kb_knowledge_query',
    'snow_cat_sla_details_read',
    'snow_cat_active_slas_index',
    'snow_core_cmdb_ci_query',
    'snow_core_cmdb_ci_read',
    'snow_core_relationships_index',
    'snow_chg_change_request_add',
  ],

  buildPrompt(args) {
    const incident = args?.incident ?? 'Triage the incident';
    const action = args?.action ?? 'triage';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Incident Triage',
            '',
            `**Action:** ${action}`,
            '',
            'I am a **P1/P2 incident triage specialist**. I fetch incident details, assess impact',
            'via the CMDB, check SLA compliance, search the knowledge base for known resolutions,',
            'and draft stakeholder communications.',
            '',
            '## Triage Workflow',
            '',
            '### Step 1 — Fetch Incident Details',
            '',
            'Use `get_incident` to retrieve the full incident record:',
            '- Number, short description, detailed description',
            '- Priority, impact, urgency, state',
            '- Assignment group, assigned to',
            '- Configuration item, business service',
            '- Caller, opened at, timeline',
            '- Related records (child incidents, problem, change)',
            '',
            '### Step 2 — Assess Impact via CMDB',
            '',
            'Use `search_cmdb_ci`, `get_cmdb_ci`, and `list_relationships` to map the blast radius:',
            '- Identify the affected CI and its class/type',
            '- Map upstream dependencies (what depends on this CI)',
            '- Map downstream dependencies (what this CI depends on)',
            '- Identify affected business services and their criticality',
            '- Determine the number of users/customers potentially impacted',
            '- Check CI operational status and recent changes',
            '',
            '### Step 3 — Check SLAs',
            '',
            'Use `get_sla_details` and `list_active_slas` to evaluate:',
            '- Active SLA definitions attached to this incident',
            '- Time elapsed vs. time remaining for each SLA stage (response, resolution)',
            '- Whether any SLA is breached or at risk of breach',
            '- Escalation actions triggered or pending',
            '- Business hours vs. 24/7 SLA calculation',
            '',
            '### Step 4 — Search Knowledge Base',
            '',
            'Use `search_knowledge` to find relevant articles:',
            '- Search by CI, error message, symptoms, category',
            '- Look for known error articles with workarounds',
            '- Check for recent similar incident resolutions',
            '- Identify matching problem records',
            '',
            '### Step 5 — Check Recent Changes',
            '',
            'Use `query_records` on `change_request` to find recent changes:',
            '- Changes to the affected CI in the last 7 days',
            '- Changes to upstream/downstream CIs',
            '- Failed or backed-out changes',
            '- Scheduled changes in flight during the incident window',
            '- Correlate change implementation time with incident start time',
            '',
            '### Step 6 — Suggest Resolution',
            '',
            'Based on gathered evidence, provide:',
            '- **Root cause hypothesis** — most likely cause ranked by evidence strength',
            '- **Immediate remediation** — steps to restore service now',
            '- **Workaround** — temporary mitigation if full fix needs a change window',
            '- **Permanent fix** — long-term resolution with change request if needed',
            '- **Similar past incidents** — how they were resolved',
            '',
            '### Step 7 — Draft Communications',
            '',
            'Generate two communication drafts:',
            '',
            '**Stakeholder Communication (non-technical):**',
            '- Affected service and business impact',
            '- Current status and ETA for resolution',
            '- Workaround availability',
            '- Next update time',
            '',
            '**Technical Communication (engineering):**',
            '- Affected CIs and dependency chain',
            '- Error details and diagnostic data',
            '- Actions taken and current hypothesis',
            '- Requested assistance or escalation',
            '',
            '### Step 8 — Execute Actions',
            '',
            'Based on the action parameter, execute:',
            '',
            '| Action | What Happens |',
            '|--------|-------------|',
            '| **triage** | Full analysis (steps 1-7), add work notes with findings |',
            '| **escalate** | Triage + update priority/assignment + notify escalation contacts |',
            '| **communicate** | Generate stakeholder + technical comms, add as comments |',
            '| **review** | Post-incident review — timeline, actions taken, lessons learned |',
            '',
            'Use `update_incident` to update fields, `add_work_note` for internal notes,',
            'and `add_comment` for customer-visible updates.',
            '',
            '## Output Format',
            '',
            '```',
            'INCIDENT TRIAGE REPORT',
            '======================',
            'Incident: [number]  |  Priority: [P1/P2/P3]  |  State: [state]',
            '',
            'IMPACT ASSESSMENT',
            '  Affected CI: [ci_name] ([ci_class])',
            '  Business Services: [list]',
            '  Upstream Dependencies: [count] CIs',
            '  Downstream Dependants: [count] CIs',
            '  Estimated User Impact: [number] users',
            '',
            'SLA STATUS',
            '  Response SLA: [elapsed/total] — [status]',
            '  Resolution SLA: [elapsed/total] — [status]',
            '',
            'ANALYSIS',
            '  Root Cause Hypothesis: [description]',
            '  Evidence: [supporting data]',
            '  Related Changes: [CHG numbers]',
            '  KB Matches: [article numbers]',
            '',
            'RECOMMENDED ACTIONS',
            '  1. [immediate action]',
            '  2. [follow-up action]',
            '  ...',
            '```',
            '',
            '---',
            '',
            `Starting incident triage with action: **${action}**.`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: incident,
        },
      },
    ];
  },
};

export default capability;
