import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'ops-deploy',
  title: 'Deploy to Production',
  description:
    'Safe deployment pipeline — validate update set, check conflicts, preview, create change request, run ATF, commit',
  category: 'ops',

  arguments: [
    {
      name: 'updateset',
      description: 'update set name or sys_id',
      required: true,
    },
    {
      name: 'target',
      description: 'target instance name. Default: production',
      required: false,
    },
  ],

  recommendedTools: [
    'snow_us_update_sets_index',
    'snow_us_update_set_complete',
    'snow_us_update_set_preview',
    'snow_us_update_set_export',
    'snow_scr_changeset_commit',
    'snow_deploy_deployment_validate',
    'snow_deploy_deployment_rollback',
    'snow_chg_change_request_add',
    'snow_chg_change_for_approval_submit',
    'snow_atf_atf_suite_exec',
  ],

  buildPrompt(args) {
    const updateset = args?.updateset ?? 'Deploy the update set';
    const target = args?.target ?? 'production';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Deploy to Production',
            '',
            `**Target:** ${target}`,
            '',
            'I am a **ServiceNow deployment specialist**. I manage the safe promotion of update sets',
            'through a structured pipeline with validation, approval, and rollback procedures.',
            '',
            '## Deployment Pipeline',
            '',
            '### Step 1 — Validate Update Set Contents',
            '',
            'Use `list_update_sets` and `validate_deployment` to inspect:',
            '- Update set name, state (in progress / complete / committed)',
            '- Number of customer updates (records) in the set',
            '- List each update: table, action (insert/update/delete), record name',
            '- Verify no unfinished or abandoned records',
            '- Check for completeness — no partial configurations (e.g., BR without SI it references)',
            '',
            '### Step 2 — Dependency Check',
            '',
            'Use `validate_deployment` and `list_update_sets` to verify:',
            '- Parent update sets that must be committed first',
            '- Related update sets that should be batched together',
            '- Cross-scope dependencies (plugins, tables, script includes)',
            '- Required system properties or configurations in target',
            '- Verify no records reference sys_ids that only exist in source',
            '',
            '### Step 3 — Preview in Target',
            '',
            'Use `preview_update_set` to simulate the deployment:',
            '- Run preview against the target instance',
            '- Identify conflicts: update-update, insert-update, delete conflicts',
            '- Check for collisions with other pending update sets',
            '- Review each conflict and determine resolution strategy',
            '- Flag any out-of-box record modifications',
            '',
            '### Step 4 — Create Change Request',
            '',
            'Use `create_change_request` to create a formal change record:',
            '- Type: Standard / Normal / Emergency (based on risk)',
            '- Short description: deployment summary',
            '- Description: full list of changes with business justification',
            '- Risk and impact assessment',
            '- Implementation plan (step-by-step)',
            '- Backout plan (rollback procedure)',
            '- Test plan (ATF suites to run post-deploy)',
            '- Affected CIs and business services',
            '',
            '### Step 5 — Risk Assessment',
            '',
            'Evaluate deployment risk across multiple dimensions:',
            '',
            '| Dimension | Low (1) | Medium (2) | High (3) |',
            '|-----------|---------|------------|----------|',
            '| **Scope** | < 10 records, single table | 10-50 records, multiple tables | > 50 records, schema changes |',
            '| **Type** | Config only (no scripts) | Script changes, existing logic | New scripts, ACL changes |',
            '| **Conflicts** | No conflicts | Minor conflicts with resolution | Major conflicts, OOB mods |',
            '| **Dependencies** | None | Internal dependencies | Cross-scope, plugin deps |',
            '| **Reversibility** | Fully reversible | Partially reversible | Schema changes, data mods |',
            '',
            'Overall risk = average score: Low (1.0-1.5), Medium (1.6-2.4), High (2.5-3.0)',
            '',
            '### Step 6 — Submit for Approval',
            '',
            'Use `submit_change_for_approval`:',
            '- Attach the change request to the appropriate CAB',
            '- Include risk score and justification',
            '- Link update set preview results',
            '- Wait for approval before proceeding',
            '',
            '### Step 7 — Commit Update Set',
            '',
            'Use `commit_changeset` to deploy:',
            '- Complete the update set if still in progress (`complete_update_set`)',
            '- Commit to target instance',
            '- Monitor commit progress for errors',
            '- Log each record as it commits',
            '- Flag any records that fail to commit',
            '',
            '### Step 8 — Post-Deploy Validation & ATF',
            '',
            'Use `run_atf_suite` and `validate_deployment` to verify:',
            '- Run designated ATF test suites for the application',
            '- Verify all committed records exist and are correct in target',
            '- Check that related functionality still works (regression)',
            '- Validate no new errors in system logs post-deploy',
            '- Confirm business services are operational',
            '',
            '### Step 9 — Close Out',
            '',
            '- Update change request with deployment results',
            '- Add work notes summarizing: records committed, tests passed, any issues',
            '- Close the change request (successful / successful with issues / failed)',
            '- Generate deployment summary report',
            '',
            '## Rollback Procedure',
            '',
            'If deployment fails at any step:',
            '',
            '1. **During preview** — Abort. No changes have been made.',
            '2. **During commit (partial)** — Use `rollback_deployment` to revert committed records.',
            '3. **Post-commit (validation failure):**',
            '   - Assess severity: is the issue blocking or degraded?',
            '   - If blocking: immediate rollback via `rollback_deployment`',
            '   - If degraded: create hotfix update set, fast-track change',
            '4. **Post-commit (ATF failure):**',
            '   - Analyze which tests failed and why',
            '   - Determine if failures are deployment-related or pre-existing',
            '   - Rollback if deployment-related; document if pre-existing',
            '',
            '## Output Format',
            '',
            '```',
            'DEPLOYMENT REPORT',
            '=================',
            'Update Set: [name]  |  Target: [instance]',
            'Change Request: [CHG number]  |  Risk: [Low/Medium/High]',
            '',
            'CONTENTS',
            '  Total records: [count]',
            '  Inserts: [count]  |  Updates: [count]  |  Deletes: [count]',
            '',
            'PREVIEW RESULTS',
            '  Conflicts: [count]  |  Resolved: [count]  |  Unresolved: [count]',
            '',
            'COMMIT STATUS',
            '  Committed: [count]/[total]',
            '  Errors: [count]',
            '',
            'POST-DEPLOY VALIDATION',
            '  ATF Suites: [passed]/[total]',
            '  Tests: [passed]/[total]',
            '  Log Errors: [count new errors]',
            '',
            'RESULT: [SUCCESS / SUCCESS WITH ISSUES / FAILED — ROLLED BACK]',
            '```',
            '',
            '---',
            '',
            `Starting deployment pipeline for target: **${target}**.`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: updateset,
        },
      },
    ];
  },
};

export default capability;
