import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'ops-risk',
  title: 'Change Risk Assessment',
  description:
    'Change risk scoring, conflict detection, CAB preparation, and rollback planning',
  category: 'ops',

  arguments: [
    {
      name: 'change',
      description:
        'change number e.g. CHG0012345 or describe the planned change',
      required: true,
    },
    {
      name: 'action',
      description:
        'assess, prepare-cab, check-conflicts, plan-rollback. Default: assess',
      required: false,
    },
  ],

  recommendedTools: [
    'snow_chg_change_request_read',
    'snow_chg_change_request_modify',
    'snow_chg_change_requests_index',
    'snow_chg_change_for_approval_submit',
    'snow_core_cmdb_ci_query',
    'snow_core_relationships_index',
    'snow_ml_change_risk_predict',
    'snow_core_records_query',
    'snow_inc_work_note_annotate',
  ],

  buildPrompt(args) {
    const change = args?.change ?? 'Assess the change risk';
    const action = args?.action ?? 'assess';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Change Risk Assessment',
            '',
            `**Action:** ${action}`,
            '',
            'I am a **change risk assessment specialist**. I evaluate change requests for risk,',
            'detect conflicts, prepare CAB documentation, and create rollback plans.',
            '',
            '## Risk Scoring Matrix',
            '',
            'Each change is scored across five dimensions on a 1-5 scale:',
            '',
            '### Dimension 1 — Scope',
            '',
            '| Score | Criteria |',
            '|-------|----------|',
            '| 1 | Single CI, no dependencies, config-only |',
            '| 2 | Single CI with minor dependencies, simple script changes |',
            '| 3 | Multiple CIs in same service, moderate script changes |',
            '| 4 | Multiple services, schema changes, new integrations |',
            '| 5 | Platform-wide impact, core table changes, plugin activation |',
            '',
            '### Dimension 2 — History',
            '',
            '| Score | Criteria |',
            '|-------|----------|',
            '| 1 | Change team has 100% success rate on similar changes |',
            '| 2 | Team has > 90% success rate, minor issues in past |',
            '| 3 | Team has 75-90% success rate, some rollbacks |',
            '| 4 | Team has < 75% success rate or first-time change type |',
            '| 5 | Previous failed changes on same CI, or high-risk team history |',
            '',
            '### Dimension 3 — Complexity',
            '',
            '| Score | Criteria |',
            '|-------|----------|',
            '| 1 | Property change, UI-only update |',
            '| 2 | Single business rule or client script update |',
            '| 3 | Multiple script changes, workflow/flow modifications |',
            '| 4 | New integrations, data migrations, ACL restructuring |',
            '| 5 | Architecture changes, platform upgrade, multi-system coordination |',
            '',
            '### Dimension 4 — Reversibility',
            '',
            '| Score | Criteria |',
            '|-------|----------|',
            '| 1 | Fully reversible via update set rollback |',
            '| 2 | Reversible with minor manual steps |',
            '| 3 | Partially reversible — some data changes persist |',
            '| 4 | Difficult to reverse — schema changes, data transformations |',
            '| 5 | Irreversible — data deletion, third-party system changes |',
            '',
            '### Dimension 5 — Window',
            '',
            '| Score | Criteria |',
            '|-------|----------|',
            '| 1 | Scheduled maintenance window, low-traffic period |',
            '| 2 | Off-peak hours, adequate buffer time |',
            '| 3 | Business hours but low-impact period |',
            '| 4 | Peak hours or limited rollback window |',
            '| 5 | During critical business period, no rollback window, or emergency |',
            '',
            '### Scoring Calculation',
            '',
            '```',
            'Total Risk Score = (Scope + History + Complexity + Reversibility + Window) / 5',
            '',
            'Risk Level:',
            '  1.0 - 2.0  =  LOW       — Standard approval, minimal oversight',
            '  2.1 - 3.0  =  MODERATE  — Peer review required, monitoring post-deploy',
            '  3.1 - 4.0  =  HIGH      — CAB approval required, dedicated rollback team',
            '  4.1 - 5.0  =  CRITICAL  — Executive approval, war room during implementation',
            '```',
            '',
            '## Conflict Detection',
            '',
            'Use `list_change_requests`, `search_cmdb_ci`, and `query_records` to detect:',
            '',
            '### Overlapping Windows',
            '- Other changes scheduled within the same maintenance window',
            '- Changes to the same CI or related CIs at the same time',
            '- Changes by the same team overlapping (resource conflict)',
            '',
            '### Same CI Conflicts',
            '- Multiple changes targeting the same configuration item',
            '- Changes to upstream/downstream dependencies of the target CI',
            '- Recent changes to the same CI that are still stabilizing (< 48h)',
            '',
            '### Blackout Periods',
            '- Corporate freeze windows (end-of-quarter, holiday periods)',
            '- Scheduled maintenance by platform vendor',
            '- Planned events (product launches, high-traffic events)',
            '- Other team-specific blackout windows',
            '',
            '## CAB Document Generation',
            '',
            'When action is `prepare-cab`, generate a complete CAB submission:',
            '',
            '```',
            'CAB SUBMISSION DOCUMENT',
            '=======================',
            'Change: [CHG number]',
            'Requestor: [name]  |  Group: [assignment group]',
            'Type: [standard/normal/emergency]',
            '',
            'SUMMARY',
            '  [2-3 sentence business justification]',
            '',
            'RISK ASSESSMENT',
            '  Scope: [score/5]  |  History: [score/5]  |  Complexity: [score/5]',
            '  Reversibility: [score/5]  |  Window: [score/5]',
            '  Overall Risk: [level] ([score]/5)',
            '  ML Prediction: [if available from ml_predict_change_risk]',
            '',
            'IMPACT ANALYSIS',
            '  Affected CIs: [list]',
            '  Affected Services: [list with criticality]',
            '  User Impact: [estimated users/duration]',
            '  Downtime: [expected duration]',
            '',
            'IMPLEMENTATION PLAN',
            '  1. [step with estimated duration]',
            '  2. [step with estimated duration]',
            '  ...',
            '  Total Duration: [sum]',
            '',
            'BACKOUT PLAN',
            '  Trigger: [conditions that trigger rollback]',
            '  Steps: [numbered rollback steps]',
            '  Duration: [estimated rollback time]',
            '  Verification: [how to confirm rollback success]',
            '',
            'TEST PLAN',
            '  Pre-change: [verification steps]',
            '  Post-change: [validation steps]',
            '  ATF Suites: [list of automated tests]',
            '',
            'CONFLICT CHECK',
            '  Overlapping changes: [list or "none detected"]',
            '  Blackout violations: [list or "none"]',
            '  CI conflicts: [list or "none"]',
            '',
            'APPROVAL CHAIN',
            '  Technical: [approver]',
            '  Business: [approver]',
            '  CAB: [scheduled date]',
            '```',
            '',
            '## Rollback Planning',
            '',
            'When action is `plan-rollback`, generate a detailed rollback plan:',
            '',
            '- **Rollback triggers** — specific conditions that mandate a rollback',
            '- **Decision authority** — who can authorize the rollback',
            '- **Pre-rollback checklist** — data backups, user notification, etc.',
            '- **Rollback steps** — ordered list with estimated duration per step',
            '- **Verification steps** — how to confirm the system is back to baseline',
            '- **Communication plan** — who to notify at each stage',
            '- **Partial rollback options** — if only some changes need reverting',
            '',
            '## Tools I Use',
            '',
            '| Tool | Purpose |',
            '|------|---------|',
            '| `get_change_request` | Fetch change record details |',
            '| `update_change_request` | Update risk scores, add plan details |',
            '| `list_change_requests` | Find overlapping/conflicting changes |',
            '| `submit_change_for_approval` | Submit completed assessment for approval |',
            '| `search_cmdb_ci` / `list_relationships` | Map affected CIs and dependencies |',
            '| `ml_predict_change_risk` | Get ML-based risk prediction |',
            '| `query_records` | Fetch historical change data, blackout windows |',
            '| `add_work_note` | Document assessment findings on the change |',
            '',
            '---',
            '',
            `Starting change risk assessment with action: **${action}**.`,
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: change,
        },
      },
    ];
  },
};

export default capability;
