import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'review-scripts',
  title: 'Bulk Script Scan',
  description:
    'Scan ALL scripts on a table or in a scope for issues — covers business rules, script includes, client scripts, UI policies, UI actions, and more',
  category: 'review',
  arguments: [
    {
      name: 'scope',
      description:
        'Table name (e.g. "incident"), scope name (e.g. "x_myapp"), or "instance" for everything',
      required: true,
    },
    {
      name: 'severity',
      description:
        'Minimum severity to report: critical, high, or all (default: all)',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_scr_business_rules_index',
    'snow_scr_script_includes_index',
    'snow_scr_client_scripts_index',
    'snow_scr_ui_policies_index',
    'snow_scr_ui_actions_index',
    'snow_core_records_query',
  ],

  buildPrompt(args) {
    const scope = args?.scope ?? 'Scan my ServiceNow scripts';
    const severity = args?.severity ?? 'all';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Bulk Script Scan',
            '',
            'I am a **ServiceNow bulk script scanner**. I scan ALL script-bearing artifacts',
            'on a table, in a scope, or across the entire instance to find security vulnerabilities,',
            'performance antipatterns, deprecated APIs, and hardcoded values.',
            '',
            `## Scan Scope: **${scope}**`,
            `## Minimum Severity: **${severity}**`,
            '',
            severity === 'all'
              ? 'I will report all findings regardless of severity.'
              : `I will only report **${severity}** severity findings and above.`,
            '',
            '## Artifacts I Scan',
            '',
            'I scan ALL script-bearing artifacts in the specified scope:',
            '',
            '| Artifact | How I Find Them |',
            '|----------|-----------------|',
            '| **Business Rules** on the table | `list_business_rules` filtered by table |',
            '| **Script Includes** in the scope | `list_script_includes` filtered by scope/API name |',
            '| **Client Scripts** on the table | `list_client_scripts` filtered by table |',
            '| **UI Policy script actions** on the table | `list_ui_policies` filtered by table, then check script fields |',
            '| **UI Actions** on the table | `list_ui_actions` filtered by table |',
            '| **Catalog Client Scripts** | `query_records` on `catalog_script_client` (if catalog table) |',
            '| **ACL advanced scripts** on the table | `query_records` on `sys_security_acl` with script != empty |',
            '| **Transform Map scripts** targeting the table | `query_records` on `sys_transform_script` |',
            '',
            '## What I Check in Every Script',
            '',
            '### 1. Injection Vulnerabilities',
            '- `eval()` or `GlideEvaluator` with user-controlled input',
            '- String concatenation in `addQuery()` or `addEncodedQuery()` — use parameterized queries',
            '- `Packages.java.*` usage for executing system commands',
            '- `GlideSecureEvaluator` bypasses',
            '- Unvalidated input in `GlideSysAttachment`, `GlideHTTPRequest`, etc.',
            '',
            '### 2. Performance Antipatterns',
            '- `GlideRecord` queries inside loops (N+1 pattern)',
            '- Missing `setLimit()` on queries that only need one record',
            '- `getRowCount()` instead of `GlideAggregate`',
            '- `current.update()` inside business rules (causes recursive saves)',
            '- `g_form.getValue()` / `g_form.setValue()` in tight loops without batching',
            '- Synchronous `GlideHTTPRequest` in before business rules',
            '- Loading full GlideRecord when only sys_id is needed (`get()` vs `addQuery`+`setLimit`)',
            '',
            '### 3. Deprecated APIs',
            '- `Packages.java.*` — removed in newer versions',
            '- `GlideRecord.getDisplayValue()` without field name',
            '- `current.variables.*` direct access — use `current.variables.getValue()`',
            '- `gs.print()` — use `gs.log()` or `gs.debug()`',
            '- `GlideRecord.insert()` returning void (check for boolean return)',
            '- `XMLDocument` / `XMLDocument2` deprecated methods',
            '',
            '### 4. Security Issues',
            '- Hardcoded credentials (passwords, API keys, tokens, Bearer strings)',
            '- Missing `gs.hasRole()` checks before privileged operations',
            '- `setWorkflow(false)` — disables business rules, bypasses security',
            '- `gs.setRedirect()` with user-controlled URLs (open redirect)',
            '- Client scripts exposing server data via `g_scratchpad` without filtering',
            '- XSS in UI Actions, UI Pages, or Service Portal widgets',
            '',
            '### 5. Hardcoded sys_ids',
            '- Any 32-character hex string that looks like a sys_id',
            '- Should be replaced with `gs.getProperty()`, system properties, or dynamic lookups',
            '- Especially critical in scoped apps (sys_ids differ between instances)',
            '',
            '## Output Format',
            '',
            '### Summary Table',
            '',
            'Counts per severity across all scanned artifacts:',
            '',
            '| Severity | Count | Artifacts Affected |',
            '|----------|-------|--------------------|',
            '| Critical | | |',
            '| High | | |',
            '| Medium | | |',
            '| Low | | |',
            '| Info | | |',
            '',
            '### Scan Coverage',
            '',
            '| Artifact Type | Count Scanned | Issues Found |',
            '|---------------|---------------|--------------|',
            '',
            '### Detailed Findings',
            '',
            'For each issue:',
            '',
            '| Field | Description |',
            '|-------|-------------|',
            '| **Severity** | Critical / High / Medium / Low / Info |',
            '| **Category** | Injection, Performance, Deprecated API, Security, Hardcoded |',
            '| **Artifact** | Name and type of the script artifact |',
            '| **Location** | Line number or section in the script |',
            '| **Issue** | What is wrong and why it matters |',
            '| **Fix** | How to fix it, with a concrete code example |',
            '',
            '## Tools I Use',
            '',
            '| Tool | Purpose |',
            '|------|---------|',
            '| `list_business_rules` | Fetch all business rules on the table |',
            '| `list_script_includes` | Fetch all script includes in the scope |',
            '| `list_client_scripts` | Fetch all client scripts on the table |',
            '| `list_ui_policies` | Fetch UI policies with script actions |',
            '| `list_ui_actions` | Fetch UI actions on the table |',
            '| `query_records` | Fetch catalog client scripts, ACL scripts, transform scripts |',
            '',
            'I will now begin the bulk script scan.',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: scope,
        },
      },
    ];
  },
};

export default capability;
