import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'review-acls',
  title: 'ACL Coverage Analysis',
  description:
    'Analyze ACL coverage across all tables and fields — find gaps, conflicts, overly permissive rules',
  category: 'review',
  arguments: [
    {
      name: 'table',
      description:
        'Specific table to audit (e.g. "incident", "cmdb_ci"), or omit for instance-wide analysis',
      required: false,
    },
  ],
  recommendedTools: [
    'snow_scr_acls_index',
    'snow_scr_acl_read',
    'snow_core_records_query',
    'snow_core_table_schema_read',
    'snow_usr_users_index',
    'snow_usr_groups_index',
  ],

  buildPrompt(args) {
    const table = args?.table ?? '';
    const scope = table || 'instance-wide';

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# ACL Coverage Analysis',
            '',
            'I am a **ServiceNow ACL analysis specialist**. I audit access control lists across',
            'tables and fields to find coverage gaps, conflicting rules, and overly permissive access.',
            '',
            `## Audit Scope: **${scope}**`,
            '',
            table
              ? `I will perform a deep ACL analysis on the \`${table}\` table and all its fields.`
              : 'I will perform an instance-wide ACL coverage analysis across all tables.',
            '',
            '## What I Check',
            '',
            '### 1. Tables with NO ACLs Defined',
            '- Identify tables that have zero ACL records — these rely solely on default security',
            '- Flag custom tables (non-OOB) with no ACLs as **Critical**',
            '- Check inherited ACLs from parent tables and whether they are sufficient',
            '',
            '### 2. Field-Level ACL Gaps',
            '- Tables with table-level ACLs but no field-level ACLs for sensitive fields',
            '- Sensitive field detection: fields named `password`, `ssn`, `credit_card`, `api_key`,',
            '  `token`, `secret`, `salary`, `dob`, `date_of_birth`, `social_security`, or custom',
            '  fields marked as encrypted',
            '- Fields containing PII or financial data without explicit field-level ACLs',
            '',
            '### 3. Wildcard / Overly Permissive ACLs',
            '- ACLs with **empty script AND empty condition** — effectively grants access to anyone with the role',
            '- ACLs with no role requirement and no condition — grants access to all authenticated users',
            '- ACLs using `*` operation type — applies to all CRUD operations indiscriminately',
            '',
            '### 4. Admin-Only Shortcut ACLs',
            '- ACLs that only require `admin` role — often a lazy shortcut',
            '- Identify where scoped roles (`x_*`) should replace admin requirements',
            '- Flag tables where admin is the only role with write access',
            '',
            '### 5. Conflicting ACLs',
            '- Multiple ACLs on the same object with different roles and different outcomes',
            '- ACLs where one grants access and another denies it for overlapping role sets',
            '- Order-of-evaluation issues where a permissive ACL runs before a restrictive one',
            '- Duplicate ACLs (same table, operation, and role)',
            '',
            '### 6. Row-Level ACL Gaps on Multi-Tenant Tables',
            '- Tables with a `company`, `department`, or `assignment_group` field but no',
            '  row-level condition restricting visibility',
            '- Multi-tenant tables where users can see records outside their org',
            '- Domain-separated instances missing domain ACL conditions',
            '',
            '### 7. Script Conditions That Could Be Simplified',
            '- ACLs with script conditions that perform simple field comparisons — these should',
            '  use the condition builder instead for better performance and maintainability',
            '- Scripts that only check `gs.hasRole()` — should use the role field instead',
            '- Scripts that only check `current.field == value` — should use a condition',
            '',
            '### 8. Missing CRUD Operation Coverage',
            '- Tables with `read` ACLs but missing `create`, `write`, or `delete` ACLs',
            '- Tables with `write` but no `delete` — users can edit but deletion is uncontrolled',
            '- Tables missing `create` ACLs — anyone can insert records',
            '- Attachment ACLs missing for tables that store sensitive attachments',
            '',
            '## Output Format',
            '',
            '### Coverage Matrix',
            '',
            'A table showing ACL coverage per table and operation:',
            '',
            '| Table | Read | Create | Write | Delete | Field-Level | Row-Level | Issues |',
            '|-------|------|--------|-------|--------|-------------|-----------|--------|',
            '',
            '### Gap List',
            '',
            'For each gap found:',
            '',
            '| Field | Description |',
            '|-------|-------------|',
            '| **Severity** | Critical / High / Medium / Low |',
            '| **Table** | Affected table |',
            '| **Gap Type** | Missing ACL, Overly Permissive, Conflict, etc. |',
            '| **Details** | What is missing or misconfigured |',
            '| **Recommendation** | Specific fix with ACL configuration |',
            '',
            '### Recommendations',
            '',
            'Prioritized list of actions to improve ACL coverage, grouped by severity.',
            '',
            '## Tools I Use',
            '',
            '| Tool | Purpose |',
            '|------|---------|',
            '| `list_acls` | Retrieve all ACLs, optionally filtered by table |',
            '| `get_acl` | Deep-dive into specific ACL configuration |',
            '| `query_records` | Check table metadata, field definitions, record counts |',
            '| `get_table_schema` | Understand table structure and field types |',
            '| `list_users` | Check user role assignments for impact analysis |',
            '| `list_groups` | Check group role assignments for impact analysis |',
            '',
            'I will now begin the ACL coverage analysis.',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: table
            ? `Analyze ACL coverage for the ${table} table`
            : 'Analyze ACL coverage across the entire instance',
        },
      },
    ];
  },
};

export default capability;
