import type { CapabilityDefinition } from '../types.js';

const capability: CapabilityDefinition = {
  name: 'scan-automation',
  title: 'Automation Conflict Scan',
  description:
    'Automation conflict detection — overlapping business rules and flows, circular triggers, execution order issues',
  category: 'scan',

  arguments: [
    {
      name: 'table',
      description:
        'Specific table to scan (e.g. "incident", "change_request"). If omitted, scans all tables with automation',
      required: false,
    },
    {
      name: 'scope',
      description:
        'Application scope to filter: "all" (default) or a specific scope (e.g. "x_myapp")',
      required: false,
    },
  ],

  recommendedTools: [
    'snow_core_records_query',
    'snow_scr_business_rules_index',
    'snow_scr_business_rule_read',
    'snow_flow_flows_index',
    'snow_flow_flow_read',
    'snow_scr_client_scripts_index',
    'snow_scr_client_script_read',
    'snow_scr_script_includes_index',
    'snow_core_table_schema_read',
  ],

  buildPrompt(args) {
    const table = args?.table ?? '';
    const scope = args?.scope ?? 'all';

    const tableLabel = table || 'All tables with automation';
    const scopeLabel =
      scope === 'all'
        ? 'Instance-wide (all scopes)'
        : `Application scope: \`${scope}\``;

    // ─── Section 1: Automation Inventory ─────────────────────────────────────

    const inventorySection = [
      '## 1. Automation Inventory',
      '',
      'Use `list_business_rules`, `list_flows`, `list_client_scripts`, and `query_records` to build',
      'a complete inventory of all automation artifacts:',
      '',
      '### Business Rules (sys_script)',
      table
        ? `Query all active business rules on \`${table}\`:`
        : 'Query all active business rules, grouped by table:',
      '- Count by timing: before, after, async, display',
      '- Count by operation: insert, update, delete, query',
      '- Note execution order (100-1000 range, lower runs first)',
      '- Flag rules with no condition (fire on every operation)',
      '',
      '### Flow Designer Flows (sys_hub_flow)',
      table
        ? `Query all active flows triggered by record changes on \`${table}\`:`
        : 'Query all active record-triggered flows, grouped by trigger table:',
      '- Count by trigger type: record insert, record update, record delete',
      '- Note trigger conditions',
      '- Identify flows with inline Script steps',
      '',
      '### Client Scripts (sys_script_client)',
      table
        ? `Query all active client scripts on \`${table}\`:`
        : 'Query all active client scripts, grouped by table:',
      '- Count by type: onLoad, onChange, onSubmit, onCellEdit',
      '- Note the trigger field for onChange scripts',
      '',
      '### Other Automation',
      '- **Scheduled Jobs** (`sysauto_script`) — recurring scripts that may interact with the same tables',
      '- **UI Actions** (`sys_ui_action`) — form/list buttons with server-side or client-side scripts',
      '- **UI Policies** (`sys_ui_policy`) — form behavior rules with script actions',
      '- **Notifications** (`sysevent_email_action`) — triggered by record changes',
      '- **Script Actions** (`sysevent_script_action`) — event-driven scripts',
      '- **Transform Map Scripts** (`sys_transform_script`) — import-related automation',
      '- **ACL Scripts** — advanced ACL conditions that run on record access',
      '',
      '**Output:** Automation inventory matrix',
      '| Table | BRs (before) | BRs (after) | BRs (async) | Flows | Client Scripts | Other | Total |',
      '|-------|-------------|-------------|-------------|-------|----------------|-------|-------|',
    ];

    // ─── Section 2: Overlapping Triggers ─────────────────────────────────────

    const overlapSection = [
      '## 2. Overlapping Trigger Detection',
      '',
      'Identify business rules and flows that may conflict because they act on the same',
      'table, operation, and timing:',
      '',
      '### Same-Field Conflicts',
      '- Two or more **before** business rules that both `setValue()` the same field on the same',
      '  table during the same operation — the one with the higher order number wins, but this is',
      '  usually unintentional',
      '- A **before** business rule and a **flow** that both try to set the same field — the BR',
      '  fires first, then the flow overwrites it (or vice versa depending on timing)',
      '- Example: BR sets `priority` based on impact/urgency, then a flow also sets `priority`',
      '  based on a different algorithm — result depends on execution order',
      '',
      '### Condition Overlap Analysis',
      '- Two rules with the same condition (or no condition) on the same table+operation',
      '  — one may be redundant, or they may have contradictory effects',
      '- Rules where one condition is a subset of another (e.g., Rule A fires when state=Active,',
      '  Rule B fires when state=Active AND priority=1 — both fire on P1 Active records)',
      '- Rules with mutually exclusive conditions that should be merged into one rule with branching logic',
      '',
      '### BR vs Flow Overlap',
      '**Execution order in ServiceNow save pipeline:**',
      '```',
      '1. Client Scripts (onSubmit) — runs in browser before server',
      '2. Before Business Rules — runs before database write (order 1-1000)',
      '3. Database write occurs',
      '4. After Business Rules — runs after database write (order 1-1000)',
      '5. Async Business Rules — queued for background execution',
      '6. Flow Designer flows — trigger evaluation and execution',
      '7. Notifications — email/SMS triggers evaluate',
      '```',
      '',
      '- A **before BR** setting a field and an **after BR** reading that field is fine (correct order)',
      '- A **before BR** setting a field and a **flow** reading the trigger record\'s field is fine',
      '  (flow sees the committed value)',
      '- A **flow** updating a field and an **after BR** on the same table — the flow\'s update triggers',
      '  the BR again (re-entrant!)',
      '',
      '**Output:**',
      '| Table | Operation | Rule 1 | Rule 2 | Conflict Type | Field(s) | Severity | Recommendation |',
      '|-------|-----------|--------|--------|---------------|----------|----------|----------------|',
    ];

    // ─── Section 3: Circular Triggers ────────────────────────────────────────

    const circularSection = [
      '## 3. Circular Trigger Detection',
      '',
      'Trace automation chains to find circular dependencies:',
      '',
      '### Direct Circular Triggers',
      '- **After BR on table A updates table B → After BR on table B updates table A**',
      '  This creates an infinite loop. ServiceNow has a recursion depth limit (typically ~5)',
      '  but hitting it wastes resources and may cause partial updates.',
      '- **Flow on table A updates table B → Flow on table B updates table A**',
      '  Same circular pattern in Flow Designer.',
      '- **Self-referential:** After BR on table A does `current.update()` → triggers itself again.',
      '  Common mistake, especially with `current.update()` in after rules.',
      '',
      '### Indirect Circular Triggers (3+ hop chains)',
      '- A → B → C → A — three-table circular chain',
      '- A → B (via BR) → C (via flow) → A (via notification script) — mixed automation types',
      '- Build a directed graph of "table A modifies table B" relationships and detect cycles',
      '',
      '### How to Detect',
      '1. For each after BR and flow, identify which tables it writes to (look for `GlideRecord`',
      '   `.insert()`, `.update()`, `.deleteRecord()` calls, and Update Record flow actions)',
      '2. Build an adjacency map: `source_table → [target_tables]`',
      '3. Run cycle detection (DFS) on the graph',
      '4. Report each cycle with the full chain of automation artifacts involved',
      '',
      '### Common Circular Patterns',
      '- Incident ↔ Task: incident BR creates task, task BR updates parent incident',
      '- Change ↔ Change Task: change request BR creates tasks, task completion BR updates change',
      '- CMDB ↔ Discovery: CI update BR triggers re-discovery, discovery updates CI',
      '- Catalog ↔ Task: request item BR creates tasks, task BR updates request item',
      '',
      '**Output:**',
      '| Cycle | Hop 1 | Hop 2 | Hop 3+ | Automation Chain | Severity | Recommendation |',
      '|-------|-------|-------|--------|------------------|----------|----------------|',
    ];

    // ─── Section 4: Execution Order Issues ───────────────────────────────────

    const orderSection = [
      '## 4. Execution Order Issues',
      '',
      'Analyze business rule execution order for conflicts:',
      '',
      '### Order Number Analysis',
      '- **Default order (100):** Most OOB and custom BRs use 100. When multiple BRs have order 100',
      '  on the same table+timing+operation, execution order is **undefined** (nondeterministic).',
      '  If these BRs depend on each other\'s output, results are unpredictable.',
      '- **Conflicting explicit orders:** Two BRs with the same explicit order number (e.g., both 200)',
      '  on the same table+timing — same nondeterminism problem.',
      '- **Anti-pattern: order 1 or 0:** Setting order to 0 or 1 to "run first" — fragile, creates',
      '  a race with other rules that also set low orders.',
      '',
      '### Dependency Ordering',
      '- **Read-after-write dependencies:** BR at order 200 reads a field that BR at order 300 sets',
      '  — the reader runs before the writer, gets stale data. Order should be swapped.',
      '- **Write-after-write dependencies:** Two BRs both set the same field but at different orders',
      '  — the last one wins. Is this intentional? Document and verify.',
      '',
      '### BR vs Flow Ordering',
      '- BRs ALWAYS fire before flows in the save pipeline',
      '- If a flow depends on a field value set by a BR, this works correctly',
      '- If a BR depends on an action taken by a flow, it will NOT work — the BR runs first',
      '- If a flow updates the same record, it triggers the BRs again (second save)',
      '',
      '### Display BR Ordering',
      '- Display BRs run when the form loads, before the user sees data',
      '- Multiple display BRs populating `g_scratchpad` — if they set the same key, last one wins',
      '- Display BRs with expensive queries slow down form load for all users',
      '',
      '**Output:**',
      '| Table | Timing | Rule 1 (Order) | Rule 2 (Order) | Issue | Impact | Recommendation |',
      '|-------|--------|----------------|----------------|-------|--------|----------------|',
    ];

    // ─── Section 5: Redundant Automation ─────────────────────────────────────

    const redundantSection = [
      '## 5. Redundant Automation Detection',
      '',
      'Find duplicated logic across different automation mechanisms:',
      '',
      '### BR + Flow Duplication',
      '- A business rule and a flow on the same table doing the same thing',
      '  (e.g., both sending a notification when state changes to "Resolved")',
      '- Common during migration from BRs to Flow Designer — old BR not deactivated',
      '- Result: duplicate emails, double updates, or conflicting field values',
      '',
      '### Client + Server Duplication',
      '- Client script validation (onSubmit) that is also enforced by a before BR',
      '  — server-side validation is correct, client-side is a UX enhancement.',
      '  This is acceptable but should be documented. Flag cases where logic differs.',
      '- Client script setting a field (onChange) that is also set by a before BR',
      '  — the BR overwrites the client script\'s value, making the client script useless',
      '',
      '### Notification Duplication',
      '- A notification AND a flow both sending emails on the same condition',
      '- A notification AND a business rule both calling `gs.eventQueue()` for the same event',
      '- Multiple notifications with overlapping conditions on the same table',
      '',
      '### Scheduled Job Overlap',
      '- Two scheduled jobs that query and update the same table on similar schedules',
      '- A scheduled job doing work that a BR or flow already handles in real-time',
      '',
      '**Output:**',
      '| Table | Duplicate 1 (Type) | Duplicate 2 (Type) | Overlapping Logic | Recommendation |',
      '|-------|--------------------|--------------------|-------------------|----------------|',
    ];

    // ─── Section 6: Performance Hotspots ─────────────────────────────────────

    const hotspotSection = [
      '## 6. Performance Hotspots',
      '',
      'Identify tables and operations where automation density creates performance risks:',
      '',
      '### Automation Density',
      '- Tables with **>10 active business rules** — high density, every save runs all of them',
      '- Tables with **>5 before-insert rules** — slows down record creation',
      '- Tables with **>5 after-update rules** — every field change triggers all of them',
      '  (unless conditions are well-scoped)',
      '- Tables where total automation count (BRs + flows + client scripts) exceeds **20**',
      '',
      '### Heavy Save Chains',
      '- Before insert chain: how many BRs fire on insert? What is the total estimated execution time?',
      '- After update chain: how many BRs + flows fire on update? Do any of them trigger additional saves?',
      '- The "cascade factor": one user save → N business rules → M of them do `current.update()` or',
      '  update other tables → triggers additional rules on those tables',
      '',
      '### Script Performance',
      '- BRs with GlideRecord queries in their scripts that run on every save (no caching)',
      '- BRs that call external APIs synchronously (before rules block the save transaction)',
      '- BRs with complex condition scripts instead of simple condition filters',
      '  (condition scripts run on every save to check if the rule should fire)',
      '',
      '### Client-Side Performance',
      '- Tables with >5 onChange client scripts — every field change fires all of them',
      '- onLoad client scripts with synchronous GlideAjax calls — blocks form rendering',
      '- Client scripts loading large datasets into g_scratchpad',
      '',
      '**Output:**',
      '| Table | Total Automation | Before Insert | After Update | Cascade Factor | Risk Level | Recommendation |',
      '|-------|------------------|---------------|--------------|----------------|------------|----------------|',
    ];

    // ─── Section 7: Async vs Sync Mismatch ──────────────────────────────────

    const asyncSection = [
      '## 7. Async vs Sync Mismatch',
      '',
      'Identify automation running in the wrong execution mode:',
      '',
      '### Should Be Async',
      '- **Before/After BRs with external callouts:** REST calls, SOAP calls, LDAP lookups.',
      '  These block the user\'s save transaction. Move to async BR or flow.',
      '- **After BRs that send emails directly:** Use event queue + notification instead',
      '  (`gs.eventQueue()` → event handler → notification)',
      '- **After BRs that update large record sets:** Updating 100+ records in an after BR',
      '  blocks the user. Move to async BR or scheduled job.',
      '- **Before BRs with heavy computation:** Complex calculations, parsing, or data',
      '  transformation that takes > 1 second. Consider caching or async approach.',
      '',
      '### Should Be Sync (But Is Async)',
      '- **Async BRs that set fields on the triggering record:** `current.update()` in async BRs',
      '  happens after the record is already committed. If another user or process reads the record',
      '  between the original save and the async update, they see stale data.',
      '- **Async BRs for data validation:** If validation fails asynchronously, the invalid record',
      '  is already saved. Validation MUST be in a before BR.',
      '- **Async BRs for field calculation:** If calculated fields need to be visible immediately',
      '  after save (e.g., priority derived from impact+urgency), use a before BR.',
      '',
      '### Async BR Limitations',
      '- `current` in async BRs is a snapshot from the time of trigger — not the live record.',
      '  If another process updates the record between trigger and execution, the async BR works',
      '  with stale data.',
      '- `previous` is available in async BRs but is also a snapshot.',
      '- Async BRs cannot abort the triggering transaction (record is already saved).',
      '- Async BRs run as the user who triggered them, but outside the original transaction scope.',
      '',
      '**Output:**',
      '| Rule Name | Table | Current Mode | Recommended Mode | Reason | Impact | Recommendation |',
      '|-----------|-------|-------------- |------------------|--------|--------|----------------|',
    ];

    // ─── Section 8: Cross-Scope Conflicts ────────────────────────────────────

    const crossScopeSection = [
      '## 8. Cross-Scope Conflicts',
      '',
      'Analyze conflicts between global scope and scoped app automation:',
      '',
      '### Global vs Scoped BRs',
      '- Global BRs on tables that are also targeted by scoped app BRs',
      '  — both fire on the same operation, potentially conflicting',
      '- Global BRs that cannot be overridden by scoped apps (no condition filter)',
      '- Scoped app BRs that assume global BRs do not exist (fragile assumption)',
      '',
      '### Scope Access Issues',
      '- Scoped app BRs accessing tables outside their scope via cross-scope privileges',
      '  — if the cross-scope access is revoked, the BR silently fails',
      '- Scoped app flows accessing global Script Includes — version dependency risk',
      '- Global BRs calling scoped app Script Includes — breaks if the scoped app is uninstalled',
      '',
      '### Upgrade Conflict Risks',
      '- Custom BRs on OOB tables with the same condition as OOB BRs — ServiceNow upgrades',
      '  may change OOB BR behavior, causing unexpected interactions with custom rules',
      '- Custom BRs with order numbers that interleave with OOB BRs — upgrade may insert new',
      '  OOB rules that change the effective execution sequence',
      '- Customized OOB BRs (modified base system rules) — will be flagged in upgrade previews',
      '',
      '**Output:**',
      '| Table | Global Rule | Scoped Rule | Scope | Conflict Type | Risk | Recommendation |',
      '|-------|-------------|-------------|-------|---------------|------|----------------|',
    ];

    // ─── Build sections ──────────────────────────────────────────────────────

    const sections: string[][] = [
      inventorySection,
      overlapSection,
      circularSection,
      orderSection,
      redundantSection,
      hotspotSection,
      asyncSection,
      crossScopeSection,
    ];

    // ─── Report Format ───────────────────────────────────────────────────────

    const reportFormat = [
      '## Automation Conflict Report Format',
      '',
      'Compile ALL findings into this structure:',
      '',
      '```',
      'AUTOMATION CONFLICT SCAN REPORT',
      '================================',
      `Table Focus: ${tableLabel}`,
      `Scope: ${scopeLabel}`,
      'Date: [current date]',
      '',
      'EXECUTIVE SUMMARY',
      '- Tables scanned: X',
      '- Total automation rules found: X',
      '- Conflicts detected: X',
      '- Circular triggers: X',
      '- Performance hotspots: X',
      '- Redundant rules: X',
      '- Overall risk: [Low / Medium / High / Critical]',
      '',
      'CONFLICT MATRIX',
      'A visual matrix showing which automation artifacts interact on each table:',
      '',
      '  Table: incident',
      '  ┌─────────────────────┬────────────────┬──────────────────┐',
      '  │ Before Insert       │ After Insert   │ Flows (Insert)   │',
      '  ├─────────────────────┼────────────────┼──────────────────┤',
      '  │ Set Priority (100)  │ Create Task    │ Notify Assignee  │',
      '  │ Validate Fields(200)│ Send Email     │ Update CMDB      │',
      '  │                     │ ↑ conflicts ↑  │                  │',
      '  └─────────────────────┴────────────────┴──────────────────┘',
      '',
      'DETAILED FINDINGS',
      '-----------------',
      'Each finding MUST include:',
      '  Finding ID:      AUTO-XXXX',
      '  Severity:        Critical / High / Medium / Low',
      '  Category:        Overlap / Circular / Order / Redundant / Performance / Async / Cross-Scope',
      '  Table:           Affected table',
      '  Rules Involved:  List of conflicting rules with types and orders',
      '  Evidence:        [specific conflict details: fields, conditions, execution trace]',
      '  Impact:          [data corruption, performance, unpredictable behavior]',
      '  Recommendation:  [merge rules, adjust order, convert to async, deactivate, etc.]',
      '',
      'SEVERITY DEFINITIONS',
      '  CRITICAL — Active data corruption or infinite loop risk',
      '  HIGH     — Conflicting rules causing unpredictable behavior',
      '  MEDIUM   — Performance risk or redundant automation',
      '  LOW      — Best practice violation; no immediate impact',
      '',
      'REMEDIATION PRIORITIES',
      '1. [Circular triggers and infinite loops — fix immediately]',
      '2. [Field-level conflicts — resolve within 1 week]',
      '3. [Performance hotspots — optimize within 2 weeks]',
      '4. [Redundant automation — clean up in next sprint]',
      '```',
    ];

    return [
      {
        role: 'assistant' as const,
        content: {
          type: 'text' as const,
          text: [
            '# Capability: Automation Conflict Scan',
            '',
            `**Table Focus:** ${tableLabel}`,
            `**Scope:** ${scopeLabel}`,
            '',
            'This capability detects conflicts, overlaps, and issues across ALL automation',
            'mechanisms in ServiceNow: business rules, flows, client scripts, scheduled jobs,',
            'UI actions, notifications, and more. Automation conflicts are one of the most',
            'common causes of data corruption, performance degradation, and unpredictable',
            'behavior in ServiceNow instances.',
            '',
            '**Platform Knowledge:**',
            '- Business rules fire BEFORE flows in the ServiceNow save pipeline',
            '- BR execution order: lower order number runs first (range 1-1000, default 100)',
            '- When multiple BRs have the same order number, execution order is nondeterministic',
            '- After BRs that call `current.update()` trigger another full save pipeline cycle',
            '- Flows trigger after all BRs complete; flow-initiated record updates trigger BRs again',
            '- Client scripts run in the browser before the server save pipeline begins',
            '- Async BRs and flows run outside the user\'s transaction context',
            '',
            ...sections.flatMap(s => [...s, '']),
            ...reportFormat,
            '',
            '---',
            '',
            'Beginning automation conflict scan. Every finding must include its Finding ID,',
            'severity, category, involved rules, concrete evidence, and a specific recommendation.',
            '',
            'After presenting your analysis, offer to generate a branded PDF or PPTX report by calling the `generate_report` tool with your full analysis.',
          ].join('\n'),
        },
      },
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: table
            ? `Run an automation conflict scan on the \`${table}\` table. Find overlapping rules, circular triggers, execution order issues, and performance hotspots. Give me a structured conflict report.`
            : `Run an automation conflict scan across all tables. Find overlapping rules, circular triggers, execution order issues, and performance hotspots. Give me a structured conflict report.`,
        },
      },
    ];
  },
};

export default capability;
